redis-rs/redis-rs

- Makefile
- README.md
- examples/basic.rs
- src/cmd.rs
- src/commands.rs
- src/connection.rs
- src/lib.rs
- src/parser.rs
- src/script.rs
- src/types.rs
- tests/test_basic.rs
Once mitsuhiko/rust-sha1#10 is merged, this PR will make sure `redis-rs` works on latest Rust again.
It includes:
* Removal of all integer suffixes
* Replacement of `range` by range syntax
* Usage of updated `io::process` module (hard-killing the server on drop now)
* Replacement of `as_slice()` everywhere with appropiate syntax
* Removal of unused features (only a few remain)
* Update of `rustc_serialize` crate name
* Rename of `RUST_TEST_TASKS` to `RUST_TEST_THREADS` in Makefile
All tests pass locally (with the updated `rust-sha1` of course).
> Pre beta fixes

- src/types.rs
- tests/test_basic.rs
The result decoding will fail for empty return values where it expected an array.
Example:
```rust
let zset : Vec<(String,u32)> = try!(con.zrangebyscore_withscores("non-existent-set", 0, 3));
```
will fail with:
```
thread '<main>' panicked at 'arithmetic operation overflowed', /home/badboy/.multirust/toolchains/stable/cargo/git/checkouts/redis-rs-44dbe34b2682f27b/master/src/types.rs:832
```
It does not fail for a simple `Vec<String>`
Returning early when we are sure there is nothing to parse will prevent this and return a useful empty vector.
> Return early if there are no items to process

- README.md
the build image was pointing to forked Travis CI location, changed to the base's travis CI build location. changed from https://travis-ci.org/harrydevnull/redis-rs to https://travis-ci.org/mitsuhiko/redis-rs
> Updated Travis CI path back to the base CI location

- src/commands.rs
I changed the wrong command of zrembyscore function from ZREMBYSCORE to ZREMRANGEBYSCORE which is the accepted one by Redis.
> Changed the wrong command in fn "zrembyscore"

- src/commands.rs
swapped the order of arguments send for ```setex```. First argument to redis  is key and the second is the ```ttl ``` in seconds and third param being the value. The signature of method is kept the same
#67
> swapped the order of arguments for setex

- src/connection.rs
Hi
I am just starting with Rust, and tried to receive messages with this library's experimental Pubsub support. The parser reads byte by byte, performing a lot of syscalls. What's your opinion on using BufReader to reduce the performance impact?
Safety not guaranteed. It still fails for me sometimes with `Invalid byte in response`
> ActualConnection: wrap BufReader around TcpStream

- src/connection.rs
- src/types.rs
Hi,
I have added a way to set read/write time out on Redis connection.
This is needed in order to be able to handle half-open TCP connection scenario when you get_message() on PubSub. Without that it may block indefinitely when physical network connection goes away without taking down the client TCP connection half (still ESTABLISHED while Redis server is gone); see: http://blog.stephencleary.com/2009/05/detection-of-half-open-dropped.html.
I have also added is_timeout() function to RedisError so you can take appropriate action in case of time out.
This could also be useful for other scenarios.
Note that I have not tested this with Unix sockets.
Regards,
Jakub
> Connection read/write timeout setting

- src/cmd.rs
So I run a few benchmarks (also the one mentioned in #81) and flamegraphs and identified the vector resize as one problem when creating the pipelined commands.
With this small change I see some improvement.
redis-rs' own benchmarks:
```
name                                        master.txt ns/iter  faster-encoding.txt ns/iter    diff ns/iter  diff %
bench_simple_getsetdel                      37,027              37,401                                  374   1.01%
bench_simple_getsetdel_pipeline             17,230              16,305                                 -925  -5.37%
bench_simple_getsetdel_pipeline_precreated  16,370              15,409                                 -961  -5.87%
```
client-benchmark on master:
```
./target/release/client-benchmark  1.30s user 0.13s system 73% …
```
> Faster encoding

- src/script.rs
The `arg` and `key` methods could only be used in a chain as
demonstrated in the docs. If `arg` and `key` are to be called
programmatically as in
for arg in &args {
invocation.arg(arg);
}
There was a borrowing error, and `invoke` could never be called. This
detaches the lifetime of the mutable borrow from the lifetime of
ScriptInvocation (specifically, says it will be shorter) to support the
above use case.
> Relax ScriptInvocation lifetimes

- build.rs
This was causing troubles with `cargo clippy` as they seem to replace
the RUSTC env variable (see https://github.com/Manishearth/rust-clippy/issues/1517)
> Don't crash if the rustc version can't be determined

- Cargo.toml
- benches/bench_basic.rs
- src/macros.rs
https://github.com/bluss/bencher/ is just a port of the builtin benchmark library which can be used on stable rust.
> Use the bencher library to let benchmarks build on stable 

- benches/bench_basic.rs
- src/cmd.rs
- src/script.rs
- src/types.rs
A couple of small and simple performance improvements I could do easily while looking through the code. There is definitely more that could be done here towards avoiding allocations but I didn't want to get sidetracked any further and that will be easier to build on top of the `&mut Vec` style as well.
```
name                                        before ns/iter  after ns/iter  diff ns/iter   diff %  speedup
bench_encode_pipeline                       498,750         515,194              16,444    3.30%   x 0.97
bench_encode_pipeline_nested                329,036         225,092            -103,944  -31.59%   x 1.46
bench_long_pipeline                         1,819,621       1,697,848          -121,773   -6.69%   x 1.07
bench_simple_getsetdel                      89,985          90,718 …
```
> perf: Avoid allocating some redundant Vec's during encoding

- src/connection.rs
get_payload_bytes was previously returning the raw channel bytes instead
of the raw payload bytes. This has been corrected.
> Fix get_payload_bytes returning channel

- .travis.yml
- Makefile
- src/connection.rs
Based on #147 to avoid the test flakiness.
Closes #147
> fix: Use write_all to guarantee that all bytes gets written 

- src/client.rs
- src/commands.rs
- src/connection.rs
- src/lib.rs
- tests/test_basic.rs
Originally, pubsub support as only available only by creating a client
and then asking for a pubsub API. The original `PubSub` type owned a
connection. This neatly avoided the issue that only certain commands are
available once calling subscribe or psubscribe; however, it's very
unfriendly to connection poolers such as r2d2
This commit makes it so that a borrowed connection may be used for
PubSub. Available commands are limited while in pubsub mode by borring
the connection mutably into a type that only exposes the allowed
commands. This API may be accessed by calling `as_pubsub` on a
`Connection`. To go back to being able to use *any* command, this
wrapper type may be dropped, and the connection should become usable
again for other purposes.
Additionally, convenience methods are added to …
> Implement flexible PubSub API

- src/connection.rs
- src/types.rs
- tests/test_basic.rs
The `is_open` method can be used in `r2d2::ManageConnection#has_broken`
to determine if the connection was closed or failed for an other reason.
Before `r2d2-redis` had no way to check if the connection broke during
the time a request was made. This meant the only way to handle
connection errors (either a problem with the network or redis server) was
to use `test_on_check_out(true)` which run the `is_valid` check before
a connection is checked out of the pool.
While this works it has an impact on the throughput because every
checkout makes a request to redis to check the connection status.
Exposing the connection status allows the user to optimize for the
"golden path" and only mark connections (and thus removing them from the
pool) if something went wrong.
As far as I know the only way …
> Expose connection status in `is_open` method.

- appveyor.yml
- src/connection.rs
- src/types.rs
- tests/test_basic.rs
`UnixStream` is not available on windows
On windows a dropped connection to redis (or a killed redis server) will
result in a `ConnectionReset` error which is triggered when trying to
write to the connection opposed to unix which fails when trying to read
data from it.
------------------------------------------------
The configuration is based on the sample from [here][1]. Since Appveyor
does not run jobs in parallel it is currently only running the tests
against stable rust to avoid slowing down the builds too much.
[1]: https://github.com/starkat99/appveyor-rust
Apart from setting up an Appveyor account I had to configure a webhook for `push` and `pull request` events. The webhook url can be found in the appveyor project settings. This is the output for the latest build of my fork: …
> Fix the compilation, test on windows and add Appveyor configuration

- .travis.yml
- Cargo.toml
- Makefile
- benches/bench_basic.rs
- src/async.rs
- src/client.rs
- src/cmd.rs
- src/connection.rs
- src/lib.rs
- src/macros.rs
- src/parser.rs
- src/script.rs
- src/types.rs
- tests/parser.rs
- tests/support/mod.rs
- tests/test_async.rs
- tests/test_basic.rs
This adds support for communicating with redis instances asynchronously using futures and tokio. Putting this up now to show the changes and additions I have done so far.
Since the current response parser is tied to reading synchronously from a `Read` instance I rewrote it using https://github.com/Marwes/combine. I choose combine since I know it (obviously) and I wanted to try the state machine support I have been working on [in tandem](https://github.com/Marwes/combine/pull/128) with this PR (this PR is what made me come up with the idea). Though I am a bit biased I do think it should be a good fit after I have worked out the bugs so I hope the change is acceptable. (I did see the Nom parser in https://github.com/mitsuhiko/redis-rs/pull/129 but didn't use it as I'd still need to code the …
> Add an async interface using futures-rs

- src/lib.rs
I'm assuming `crate` was meant, instead of `create` :)
> Fix docs typo

- src/cmd.rs
- tests/test_basic.rs
This change allows a performance sensitive tight loop to reuse a
Pipeline object instead of allocating a new one each time.
- `with_capacity` allows to preallocate the internal `commands` vector
to the specified capacity.
- `Pipeline.query_clear()` clears the internal `commands` vector from
values after the query (but keeps the allocated capacity).
- The unitests show the expected behaviour of `query` vs `query_clear`.
> Allow a more efficient pattern of Pipeline memory allocation

- src/async.rs
Modeling it as a `Sink` instead lets us use the `forward` combinator
which removes a big chunk of complicated code.
> refactor(async): Simplify the implicit pipelining

- src/parser.rs
`ValueFuture` is a hidden type so it isn't possible to see what it
returns. We can instead use `impl Future` to document that while keeping
it hidden.
cc #193
> doc: Document what `parse_async` returns with `impl Future`

- Cargo.toml
- src/async.rs
- src/lib.rs
These are slightly faster than the ones from `futures` so since we
already use `tokio` there is no harm in using these types instead.
```
query/simple_getsetdel_async
time:   [150.96 us 154.48 us 158.39 us]
change: [-30.815% -29.179% -27.560%] (p = 0.00 < 0.05)
Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
6 (6.00%) high mild
7 (7.00%) high severe
query_pipeline/shared_async_implicit_pipeline
time:   [5.5211 ms 5.5509 ms 5.5852 ms]
thrpt:  [179.04 Kelem/s 180.15 Kelem/s 181.12 Kelem/s]
change:
time:   [-11.816% -11.045% -10.262%] (p = 0.00 < 0.05)
thrpt:  [+11.436% +12.416% +13.400%]
Performance has improved.
Found 11 outliers among 100 measurements (11.00%)
6 (6.00%) low mild
3 (3.00%) high mild
2 (2.00%) high severe
query_pipeline/shared_async_long_pipeline …
```
> perf(async): Use tokio_sync's channels instead of futures

- Cargo.toml
- benches/bench_basic.rs
- src/parser.rs
- tests/parser.rs
- tests/support/mod.rs
`take_until_bytes` uses `memchr` to find the next end of line + some
minor changes to use the fact that we know that `line` contains `\r\n`
at the end.
```
decode                  time:   [2.1868 us 2.2129 us 2.2494 us]
change: [-30.297% -29.538% -28.706%] (p = 0.00 < 0.05)
Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
2 (2.00%) high mild
1 (1.00%) high severe
```
>  perf(parser): Use more performant operations for line parsing

- src/async.rs
Changes `SharedConnection` to collect the values in the worker task
before sending sending them back instead of sending each response value
in it's own `oneshot`.
This should generally improve performance for pipelined queries since
both allocations and synchronization is reduced. The only downside is
that there is no way to read responses as each one comes in but this
isn't used today.
(I wouldn't put to much stock in the exact numbers as they have pretty high variance, however this PR should always do less work than before).
```
query/simple_getsetdel_async
time:   [190.66 us 196.74 us 203.39 us]a
change: [-10.222% -6.5229% -2.8090%] (p = 0.00 < 0.05)
Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild …
```
> perf(async): Only allocate one oneshot per request

- Cargo.toml
- benches/bench_basic.rs
- src/cmd.rs
- src/commands.rs
- src/lib.rs
- src/types.rs
- tests/test_basic.rs
Not as important as `IO` latency but can still be a decent throughput improvement.
(Lots of variance in the benchmarks but there is still some clear improvements)
```
encode/pipeline         time:   [727.07 us 731.89 us 737.21 us]
change: [-59.635% -58.716% -57.668%] (p = 0.00 < 0.05)
Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
2 (2.00%) high mild
4 (4.00%) high severe
encode/pipeline_nested  time:   [246.61 us 249.05 us 251.81 us]
change: [-71.597% -70.950% -70.333%] (p = 0.00 < 0.05)
Performance has improved.
encode/integer          time:   [693.79 us 698.95 us 703.98 us]
change: [-63.633% -63.125% -62.651%] (p = 0.00 < 0.05)
Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
4 (4.00%) high mild
encode/small            time:   [1.1458 …
```
> perf: Optimize the command encoding

- Cargo.toml
- Makefile
- src/lib.rs
- src/types.rs
- tests/test_basic.rs
rustc-serialize is long deprecated.
JSON (de)serialization can be handled by the user outside of redis-rs
> Remove rustc-serialize feature

- src/lib.rs
To implement `ToRedisArgs` outside this crate,  RedisWrite needs to be publicly exposed.
> Expose RedisWrite

- src/script.rs
- tests/test_async.rs
resolves https://github.com/mitsuhiko/redis-rs/issues/175
also changes Script and ScriptInvocation to use an Arc so that the value lasts for the execution of the future
> feat: Script.invoke_async

- .gitignore
Just getting started with Rust and was looking at some popular libraries and noticed this redundant path.
> Update .gitignore to remove redundant target path

- src/parser.rs
In following case, command sending is **1,000ms** over consuming.
- When using SharedConnection
- When sending few megabytes large object via SET
The cause is that `BytesMut.extend` is expanding by the iterator.
( For example, 1MB data is executed 1,000,000 times loop and too many allocations. 🤔  )
Instead, using `Bytes.extend_from_slice` will really improve performance.
Examples below:
```rust
let mut buf = Vec::new();
File::open("/path/to/large/file")
.unwrap()
.read_to_end(&mut buf).unwrap();
let bytes = Bytes::from(buf);
let client = redis::Client::open("redis://127.0.0.1:6379").unwrap();
let instant = Instant::now();
let f = client.get_shared_async_connection()
.and_then(move |conn| {
redis::cmd("SET")
.arg("aaa")
.arg(bytes.as_ref())
.query_async(conn)
})
.map(move |(_, _): (_, …
```
> Fix seriously performance problem for SharedConnection 

- README.md
- src/cmd.rs
- src/connection.rs
- src/script.rs
- src/types.rs
- tests/parser.rs
- tests/test_async.rs
- tests/test_basic.rs
A recent-ish version of Rust nightly deprecated bare trait objects. This PR adds `dyn` to all trait objects in order to get rid of the warning.
> Fix "Trait object without an explicit dyn is deprecated" warnings

- src/commands.rs
The wrapper for `SINTERSTORE` was incorrectly `sdinterstore`, probably a copy-paste mishap since the previous ones in the series are `sdiff...`
> Fix SINTERSTORE wrapper name

- Cargo.toml
- appveyor.yml
- src/aio.rs
- src/client.rs
- src/lib.rs
Currently, SharedConnection only works on tokio 0.1 runtime.
Because it depends on `tokio_executor::spawn` (with tokio 0.1.x).
( https://github.com/mitsuhiko/redis-rs/blob/master/src/aio.rs#L437
I want to use SharedConnection with `async/await` in tokio 0.3.
In this PR, for that purpose, make it can be specified Executor from outside without depending on a specific Executor.
( This way is also adopted for [hyper](https://github.com/hyperium/hyper/blob/c71abe5c208de4f1a488cad5f3c68509e7a89266/src/server/conn.rs#L313) , [rusoto](https://github.com/rusoto/rusoto/pull/1472), and more.
For example, 0.3 Executor will work with 0.1 adapter as below:
```rust
let client = redis::Client::open("redis://127.0.0.1:6379").unwrap();
let executor = DefaultExecutor::current(); // This is tokio 0.3 …
```
> Allow running SharedConnection with any other runtime

- src/script.rs
- tests/test_async.rs
Previously, invoking a script with a complex return type would cause the following error: `Response was of incompatible type: "Not a bulk response" (response was string data('"4b98bef92b171357ddc437b395c7c1a5145ca2bd"'))`
This was because the Future returned when loading the script into the DB returns the hash of the script, and thus the return type of String would not match the intended return type.
This commit adds an enum to account for the different Future return types.
Apologies for not catching this originally!
> Fix Script::invoke_async return type error

- src/script.rs
Instead of specifying a SharedConnection. This enables wrapping the SharedConnection with another type that implements the appropriate traits.
I needed this in order to build a connection wrapper (also discussed in https://github.com/mitsuhiko/redis-rs/issues/218) that implements reconnection logic.
> Make Script#invoke_async generic over aio::ConnectionLike

- src/connection.rs
`redis::transaction` takes a closure that returns a value, and it returns that value itself if the value is Option::Some. There is no use of FromRedisValue in `transaction`, so it's not clear why this trait bound is required. It seems perfectly valid to return something that will never be serialized/deserialized with redis, such as a struct containing metrics about the statements run in the transaction.
> Do not require transaction to use FromRedisValue

- src/commands.rs
This doesn't seem to be version specific (the command hasn't changed since 2.0.0) and the documentation is available [here][1]. It looks like this was just an oversight or a copy paste issue. 
Right now attempting to use the command gives the following error:
```
An error was signalled by the server: unknown command `ZREMBYRANK`
```
[1]: https://redis.io/commands/zremrangebyrank
> Fix the command verb being sent to redis for zremrangebyrank

- benches/bench_basic.rs
- examples/basic.rs
- src/commands.rs
- src/connection.rs
- src/lib.rs
- tests/test_basic.rs
0b314e2 
It is currently possible to call `set`,`get` etc on a connection and
run the query directly but it isn't possible to create a `Cmd` struct
without running the query (except for `Pipeline`).
This adds this capability with just some small tweaks to the macro
allowing `Cmd::set("abc", 123)` to be used etc.
af5fc36
A simple `impl Pipeline` block will do the trick here.
Remove any imports of PipelineCommands
> Add Cmd::get, Cmd::set and remove PipelineCommands

- src/client.rs
> Fix docs typo tokio-executor -> tokio-rt-core

- Cargo.toml
- Makefile
- benches/bench_basic.rs
- examples/async-await.rs
- examples/basic.rs
- src/cluster.rs
- src/commands.rs
- src/connection.rs
- src/lib.rs
- src/parser.rs
- src/script.rs
- tests/test_async.rs
Clippy was run without a profile, which is not checking anything.
I've enabled `clippy::all` now and disabled individual lints where they didn't make sense.
> Fix all clippy lints

- Cargo.toml
- src/aio.rs
- src/connection.rs
- src/lib.rs
- src/parser.rs
- src/script.rs
- tests/test_async.rs
- tests/test_basic.rs
- tests/test_cluster.rs
This cuts down the default dependencies:
```
redis v0.15.2-alpha.0
├── bytes v0.5.3
├── combine v3.8.1
│   ├── ascii v0.9.3
│   ├── byteorder v1.3.2
│   ├── either v1.5.2
│   ├── memchr v2.2.1
│   └── unreachable v1.0.0
│       └── void v1.0.2
├── dtoa v0.4.4
├── futures-executor v0.3.1
│   ├── futures-core v0.3.1
│   ├── futures-task v0.3.1
│   └── futures-util v0.3.1
│       ├── futures-core v0.3.1 (*)
│       ├── futures-sink v0.3.1
│       ├── futures-task v0.3.1 (*)
│       └── pin-utils v0.1.0-alpha.4
├── futures-util v0.3.1 (*)
├── itoa v0.4.4
├── percent-encoding v2.1.0
├── tokio v0.2.9
│   ├── bytes v0.5.3 (*)
│   └── pin-project-lite v0.1.2
└── url v2.1.0
├── idna v0.2.0
│   ├── matches v0.1.8
│   ├── unicode-bidi v0.3.4
│   │   └── matches v0.1.8 (*)
│   └── …
```
> Cut further done on dependencies (make script optional)

- .travis.yml
- Cargo.toml
- benches/bench_basic.rs
- src/aio.rs
- src/client.rs
- src/cmd.rs
- src/connection.rs
- src/lib.rs
- src/parser.rs
- src/types.rs
- tests/parser.rs
- tests/test_async.rs
- tests/test_basic.rs
Updates to `combine-4` which pulls the decoding logic into combine itself, allowing redis to only call a pair of macros (for sync and async code respectively). The buffering has been moved into the `Decoder` struct provided by `combine` which avoids some unnecessary copying that the previous implementation did and the `BufReader` were therefore removed.
The `Parser` type now only persists the buffer and takes the `Read` instance in `parse_value`
> feat: Let async dependencies like tokio be avoided in sync code

- src/cluster.rs
Fix key position for stream commands:
- `xgroup` and `xinfo` have key position on 3rd place
- `xread` and `xreadgroup` have key right after **STREAMS** keyword
Small note: `xread` and `xreadgroup` command can take multiple streams (multiple keys) and my proposed solution is calculating hash only based on first key.  
I think this assumption is correct because 2 things could happen:
- all stream keys will belong to the same slot, so no point of calculating slot for each key (highly unlikely)
- some stream keys will map to different slots, then no matter how we calculate routing, redis command will fail with error: `(error) CROSSSLOT Keys in request don't hash to the same slot`
> Fix some low level stream commands for redis cluster

- src/lib.rs
The second commit removes the incomplete breaking-changes list in the docs.
> Wrap whole aio doc in the feature gate

- Cargo.toml
- examples/async-connection-loss.rs
- src/aio.rs
- src/client.rs
- src/lib.rs
- src/types.rs
Early draft of a ConnectionManager that would address the reconnect behavior discussed in #218.
Would be great to get some feedback on it. @Marwes you've written something like this in the past, right?
To test, run `cargo run --example async-connection-loss --features="tokio-rt-core" reconnect` and then restart and/or stop redis. Output for a 2s server downtime:
```
PING
Query result: Ok("PONG")
PING
Query result: Ok("PONG")
PING
Connection lost, reconnecting
Reconnecting failed: Connection refused (os error 111)
Query result: Err(broken pipe)
PING
Connection lost, reconnecting
Reconnecting failed: Connection refused (os error 111)
Query result: Err(broken pipe)
PING
Connection lost, reconnecting
Query result: Err(broken pipe)
PING
Query result: Ok("PONG")
```
I'll add some comments …
> Connection manager

- rustfmt.toml
- src/connection.rs
- src/parser.rs
- src/types.rs
- tests/test_async.rs
- tests/test_basic.rs
The underlying read may just return 0 (indicating eof), which will
then propagate to the next parse attempt which explicitly handles end of
file and returns the error.
Had to alter the test case so it works on redis < 5
Fixes #320
> fix: Return UnexpectedEof if we try to decode at eof

- Cargo.toml
- src/aio.rs
- src/cmd.rs
- src/commands.rs
- src/lib.rs
- tests/test_async.rs
Following the pattern set by Iter, I implemented an AsyncIter and exposed it up through AsyncCommands.  Thanks to @Marwes who helped me a lot.
Unfortunately I'm on Windows, so I don't have redis-server installed and I can't run the tests myself.  I usually use Docker to run redis.
> Support *SCAN methods on async connections

- src/aio.rs
- src/connection.rs
- src/lib.rs
- tests/support/mod.rs
Related #330
The unix socket URL parsing is wrong (see #132). Would like to fix it but we need discussion the URL format. Seems `url` crate does not support empty host (see https://github.com/servo/rust-url/issues/25), the alternative format with queries may be acceptable:
```
redix+unix:///<path>[?db=<db>[&pass=<password>][&user=<username>]]
```
Possibly no. If an URL does not contain `username`, it would behave in the old fashion.
Any input are welcome.
> Redis 6 AUTH <username> <password>

- CHANGELOG.md
- Cargo.toml
- examples/streams.rs
- src/commands.rs
- src/lib.rs
- src/streams.rs
- src/types.rs
- tests/test_streams.rs
This change set adds high-level wrappers for the Redis Streams commands (`XREAD`, `XADD`, etc).  This is effectively a merge of https://github.com/grippy/redis-streams-rs into `redis-rs`.
Adds a feature `streams` which is turned on by default (following the example of `geo`). Adds tests for the new commands.  Adds an example of usage.
Resolves #162.
_These changes deliver a significant feature set which was requested in August 2018._
This body of work was produced by @grippy and the contributors in https://github.com/grippy/redis-streams-rs.  Thanks for making this available to the community!
> Add Redis Streams commands

- src/aio.rs
- tests/test_async.rs
The driver future were never polled during the authentiction step.
Fixes #343
> fix: Don't hang in password authentication using a multiplexed connection

- README.md
This was a minor pain point that we encountered in #319 and #345.  Hopefully the explicit documentation can help people save a few minutes.
> Update README: suggest clippy for local dev

- src/cmd.rs
- src/geo.rs
- src/types.rs
Can help avoid allocations when writing redis arguments
> perf: Add write_arg_fmt to RedisWrite

- src/commands.rs
This allows users to call zpopmin and zpopmax commands without directly
using cmd.
> Added support for zpopmin and zpopmax

- .travis.yml
- Cargo.toml
- src/acl.rs
- src/commands.rs
- src/lib.rs
- tests/test_acl.rs
Resolves #330
Add high-level command of all [`ACL` commands](https://redis.io/topics/acl) introduced in Redis 6.
> Add Redis 6 ACL commands support

- .travis.yml
They are especially annoying because sometimes people enable travis on their forks and thus end up spamming the channel.
```
* Joins: travis-ci (~travis-ci@30.30.237.35.bc.googleusercontent.com)
<travis-ci> gferon/redis-rs#2 (redis-tls - 209c11d : Gabriel Féron): The build has errored.
<travis-ci> Change view : https://github.com/gferon/redis-rs/compare/3de1a6a8042b...209c11dc2513
<travis-ci> Build details : https://travis-ci.com/gferon/redis-rs/builds/174679889
* Parts: travis-ci (~travis-ci@30.30.237.35.bc.googleusercontent.com)
* Quits: lastmikoi (~lastmikoi@195.154.38.38) (Quit: ...)
* Joins: jarthur_ (~jarthur@2605:6000:1019:48d9:3940:9517:7a97:598a)
<+Pallets> <tachyondecay_discord> > Can I dynamically create the values for the AnyOf validator? @Smye Glancing at the docs/source …
```
> Remove spammy travis IRC notifications

- examples/streams.rs
This change set significantly improves the value of the streams example.
Unfortunately I did not include the call to `XACK` in the first pass!  I apologize for that!
Without some use of `XACK` to [signal back to Redis that each message has been correctly processed](https://redis.io/commands/xack), the example is misleading.
> Use XACK in streams example

- CHANGELOG.md
- src/client.rs
- src/connection.rs
A TCP connection only needs a host and a port.
These can be passed in as a tuple now:
redis::Client::open(("127.0.0.1", 6379))
In addition one should be able to specify an interface:
redis::Client::open(("fe80::cafe:beef%eno1", 6379))
Fixes #293
--- 
Opening to get a CI run
> Create a connection from a host and port.

- .travis.yml
Build Redis 6.0.6 from source in .travis.yml
This makes it possible to also remove stunnel but that will require more substantial changes to the integration tests
> Build Redis with TLS support in CI

- src/cmd.rs
- tests/test_async.rs
Break the loop after processing the initial results, when cursor == None. This prevents duplicate results when processing small batches. Fixes #377 
Tested with various batch sizes: 10, 100, 1000, 10.000, 100.000
> Break the loop after processing the initial results, when cursor == None

- src/lib.rs
First of all, thank you for this library - it's been a joy to use!
This is my anecdotal story: I was trying to use the [`MEMORY USAGE`](https://redis.io/commands/memory-usage) command in a tool I'm writing.  It's not implemented as a function in the library, so I was using `redis::cmd`:
```rust
let size: Option<usize> = redis::cmd("MEMORY USAGE").arg("my_key").query(con);
```
However, I was getting a (somewhat misleading) error:
```
An error was signalled by the server: unknown command `MEMORY USAGE`, with args beginning with: `my_key`
```
I spent a good amount of time trying to figure out if `MEMORY USAGE` was disabled for security reasons on my local Redis for some reason, if I was somehow running it against an old version of Redis, etc.
Eventually, I found some of the `ACL` commands in …
> Add a note about sub-commands to the "Executing Low-Level Commands" documentation

- Cargo.toml
- Makefile
- README.md
- src/lib.rs
This would refine docs on docs.rs to display feature-listing markers.
- Set `RUSTDOCFLAGS="--cfg docsrs"` for [docs.rs](https://docs.rs/about/builds#detecting-docsrs) metadata
- Update `make docs` to use nightly compiler for feature-listing markers
- Warn for `#![cfg_attr(docsrs, warn(broken_intra_doc_links))]`
> Display feature-listing markers on docs

- src/connection.rs
- src/lib.rs
Using a password for unix protocol is not working from url, this can fix it by reading password from query string instead
> Use password from query string for unix instead of password param which is not supported by url::Url

- src/types.rs
Previously, the tls error was consumed and dropped by the From trait
implementation. This makes debugging difficult when there is a TLS error
as the only output is "TLS error". This change will serialize the error
that's passed in as a debug detail.
> Converts native_tls::Error to WithDescriptionAndDetail

- tests/parser.rs
This could have caused problems if the inner reader initialized, but
didn't fill the entire initialized section. Did not appear to happens in
any of the tests using this though.
> test: Correct the usage of ReadBuf in tests

- src/types.rs
- tests/test_types.rs
Rebase of #372
Should resolve #324. I changed the ToRedisArgs implementation of booleans to encode them as 1 or 0 as redis does, and their FromRedisValue implementation to also parse from Value::Data. The latter change means that calling GET on boolean values should stop dying now.
Closes #372
`bool` are now written as `0` and `1` instead of `true` and `false`. Parsing a `bool` still accept `true` and `false` so this should not break anything for must users however if you are reading something out that was stored as a `bool` you may see different results.
> Fix bool parse errors

- .clog.toml
- CHANGELOG.md
- Cargo.toml
- README.md
Will need to run cargo release manually after this, probably some things I missed in the changelog but I'd rather just roll this out now
> Release 0.18

- Cargo.toml
- src/aio.rs
The version `0.4.4` of `arc-swap` has been yanked and prevent compiling `redis-rs`.
> Bumped arc-swap to v1.1.0

- src/aio.rs
- src/connection.rs
- tests/test_basic.rs
When connecting to redis v5 server, with uri containing username, connection
fails with an error:
wrong number of arguments for 'auth' command
library can do better and try AUTH again without username.
Signed-off-by: Nikola Pajkovsky <nikola@pajkovsky.cz>
> AUTH cmd fallback

- src/cluster.rs
- src/types.rs
- tests/support/cluster.rs
- tests/test_cluster.rs
The current implementation does not handle the `"MOVED"` error properly. Therefore, throwing an update query to a `readonly` connection will result in an infinite loop. A `readonly` connection throws the query to a replica, but a replica can not handle the update query and returns `"MOVED"`. Calling `refresh_slots` does not complete the process, because it doesn't assign the query to the master node.
I don't know if it's correct to perform the update query on a `readonly` connection, but it is possible to complete the query on the node referred to by `MOVED`.
#285 tried to solve the same problem but did not merge. In this PR, we call the `refresh_slots` method even if the query is performed on a `MOVED` destination. Also, I add a test to reproduce the infinite loop(Actually, it retries …
> Follow MOVED (again)

- README.md
Closes #387
Now redis 0.19.0 compiles with these features enabled.
I removed the "tls" feature for tokio and async-std because I think it is redundant.
Just to be clear, I haven't tested if it works, just that it compiles.
> README: update TLS instructions

- src/cmd.rs
- src/commands.rs
- src/connection.rs
- src/lib.rs
- src/pipeline.rs
Moves all logic related to Pipeline into a new file (pipeline.rs).
Main motivation for this is to reduce the size/bloat of my PR for implementing pipeline support in Cluster mode (#307).
> Refactor Pipeline logic into it's own file

- Cargo.toml
- Makefile
- benches/bench_basic.rs
- benches/bench_cluster.rs
- tests/support/cluster.rs
Adds a minimal benchmark for the basic operations against Redis Cluster. The benchmark harness will spin up a 6 node Cluster (3
primary, 3 secondary) in the way the test harness does.
Also includes fixes for:
* Makefile bench target (removes unknown "--test-threads=1" flag)
* Fixes compiler warning about unnecessary "mut" in bench_basic.rs
> Add basic benchmark for Redis Cluster

- src/aio.rs
- src/connection.rs
- tests/test_async.rs
- tests/test_basic.rs
When a `MULTI/EXEC` transaction fails due to errors, the remaining responses should be read instead of returning early. This fixes #436.
> Fix #436: Read remaining responses in case of an error

- src/cluster.rs
- src/cluster_client.rs
- src/lib.rs
Pulls all the logic around building/creating a ClusterClient into
a separate file.
Also updates some of the comments to add internal links.
> Refactor ClusterClient into it's own file

- src/aio.rs
Exposes `aio::{Multiplexed,}Connection::new` which allows these
connections to be constructed from anything implementing `AsyncRead + AsyncWrite`.
In turn this should things like mTLS #393 (since the TLSStream can be
constructed outside of redis-rs).
cc @npajkovsky
> feat(aio): Allow the underlying IO stream to be customized

- src/cluster.rs
- src/cluster_routing.rs
- src/lib.rs
Pulls all the logic related to determining and tracking which
node(s) should handle a request into a separate file.
Additional changes:
* Remove redundant check_connection function.
This is the last purely refactoring change in regards to making #307 a smaller PR.
> Refactor cluster routing logic into its own file

- src/cluster.rs
- src/cluster_routing.rs
- src/cmd.rs
- src/connection.rs
Adds a new function to the `ConnectionLike` trait that accepts a reference to a `Cmd`. This allows different connections to handle the `Cmd` as necessary. For a single Redis instance, there is no difference, but for Redis Cluster it allows the `Cmd` to be routed without needing to first parse it back into a `Value`.
This results in a *slight* performance increase when issuing commands with a `ClusterConnection`, with the performance benefits becoming more prominent with more commands. With the upcoming work to add pipeline support with Redis Cluster (#307), I observed a 42% reduction in execution time when issuing a pipeline query with 100 elements.
For backwards compatability, a new trait `Routable` is introduced and the code that determines which node(s) should handle a
particular …
> Support for requesting `Cmds` directly from a `Connection`

- benches/bench_cluster.rs
- src/cluster.rs
- src/cluster_pipeline.rs
- src/commands.rs
- src/lib.rs
- src/pipeline.rs
- tests/test_cluster.rs
Introduces a new pipeline type (`ClusterPipeline`) that allows pipelining commands to a Redis Cluster. The current implementation is **very basic and inefficient** - each command in the pipeline is serially and synchronously issued to the proper backing Redis node. However, it lays the groundwork to introduce efficient pipelining in #307.
A `ClusterPipeline` and `Pipeline` share most of the same functionality, so all common methods have been refactored into a macro to avoid code duplication. I opted to do this instead of using a trait to avoid making this a breaking change (otherwise any existing code using `Pipeline` would fail to compile until the new trait was brought into scope).
> Groundwork for pipelining with Redis Cluster

- src/aio.rs
This is similar to the PubSub helper only it's for using the Redis
MONITOR command.
Example usage:
let mut monitor = con.into_monitor();
monitor.monitor().await?;
let mut stream = monitor.on_message::<String>();
while let Some(msg) = stream.next().await {
println!("Monitor: {}", msg);
}
Closes #371
> feat: Adds a way to MONITOR a Redis connection in async

- Cargo.toml
- src/types.rs
- tests/test_types.rs
Add an implementation of `FromRedisValue` for converting `Value::Data` to `bytes::Bytes`. This is behind a `bytes-comp` feature.
> add support for converting binary data to bytes::Bytes

- Cargo.toml
- tests/support/mod.rs
Resolve these two RustSec advisories:
- [RUSTSEC-2018-0017](https://rustsec.org/advisories/RUSTSEC-2018-0017.html)
- [RUSTSEC-2020-0016](https://rustsec.org/advisories/RUSTSEC-2020-0016.html)
> Replace deprecated crates

- src/client.rs
This allows consumers to peak into the `Client's` `connection_info` field. Here's an issue about the same: https://github.com/mitsuhiko/redis-rs/issues/480#issue-867822352
Fix: https://github.com/mitsuhiko/redis-rs/issues/480
> Add get_connection_info method to `Client` struct

- src/aio.rs
It's very unclear in the docs that this is not just enabled by the "aio" feature, but rather the "connection-manager" feature.
> docs: add "connection-manager" cfg attr to aio

- benches/bench_basic.rs
- src/aio.rs
- src/client.rs
- src/connection.rs
- src/streams.rs
- src/types.rs
- tests/test_acl.rs
- tests/test_basic.rs
- tests/test_streams.rs
- tests/test_types.rs
Apply clippy hints.
__Breaking change__: update return type for `parse_redis_url` from `Result<url::Url, ()>` to `Option<url::Url>`.
Previous error value (which was an empty tuple) has very little meaning.
So as clippy says `Option` is probably a better choice.
__Other changes__:
- Avoid  calling `Ok(...?)`
- Use `mem::take` instead of `mem::replace`
- Disable some clippy warns where clippy may be wrong
- Use `Iterator::flatten`
- Use `sort_unsable` for primitive types
- Use `assert!` macro where value has no real meaning
__Note__: benchmark API still use legacy API. So `make lint` will continue complaining.
I can provide update in a dedicated MR or update this one. It is up to repository maintainer.
> Fix clippy warn and errors

- Cargo.toml
- examples/async-scan.rs
- src/cmd.rs
This allow user to use `futures_util::StreamExt`, so all the functions like map / collect / filter / etc becames availables for scans commands.
See [StreamExt API](https://docs.rs/futures-util/0.3.15/futures_util/stream/trait.StreamExt.html).
> Impl futures_util::Stream for redis::cmd::AsyncIter

- src/aio.rs
- src/aio/async_std.rs
- src/client.rs
- src/cluster.rs
- src/cluster_client.rs
- src/connection.rs
- src/lib.rs
- tests/support/mod.rs
- tests/test_async.rs
By doing this split we allow users to just pass an already established
connection plus a `RedisConnectionInfo` object to initialize a `Client`,
thus bypassing the need to construct a full `ConnectionInfo` object.
The redis specific fields of `ConnectionInfo` has been moved under a
`redis` field.
Some signatures now only take `RedisConnectionInfo` instead of a full
`ConnectionInfo`
> refactor: Split up the connection and redis connection information

- Cargo.toml
- src/aio.rs
- src/parser.rs
The async decoder would return unexpected end of input errors forever
instead of `None` to indicate that the stream was done. Since the
`MultiplexedConnection` would just drop these errors if there was no
in_flight requests, ending up in an infinite loop inside `poll_read` on
shutdown.
cc #488
> fix: Don't loop forever on shutdown of the multiplexed connection

- Cargo.toml
fixes #515:
> error[E0432]: unresolved import `futures_util::Stream`
> fix: pin futures-util dependency to required version

- src/commands.rs
Add `zscore_multiple` function in connection object to execute [redis zmscore command](https://redis.io/commands/zmscore).
This PR resolves #528.
> Add zmscore command

- Cargo.lock
- Cargo.toml
- tests/test_cluster.rs
Some other crate changed their feature flags in a breaking manner
which seems to have removed the `futures-util/alloc` feature we
implicitly relied on.
Fixes #531
> fix: Compile with tokio-comp and up-to-date dependencies

- Cargo.lock
- src/aio.rs
- src/parser.rs
Fixes #558
ValueCodec puts Redis protocol errors in `Decoder::Err`, but the new Framed updates in tokio-util 0.6.9 now cause a (simulated) end-of-stream when a decoder error is encountered. This fix puts protocol errors in `Decoder::Item` instead, by wrapping the Value in an additional RedisResult. This makes `Decoder::Err` contain exclusively parse errors.
This does mean two nested RedisResults, but I believe none of this API is public, so it's only ugly on the inside. 🙃
> Fix for changes to Framed in tokio-util 0.6.9

- src/commands.rs
This PR aims to add the following new list commands:
From v6.2.0:
1. [BLMOVE](https://redis.io/commands/blmove)
2. [LMOVE](https://redis.io/commands/lmove)
From v7.0.0:
1. [BLMPOP](https://redis.io/commands/blmpop)
2. [LMPOP](https://redis.io/commands/lmpop)
As this is my first contribution please let me know if anything needs amending about the PR. Looking for guidance in some areas as I am unfamiliar with the code but will comment on the code in these areas.
> Add new list commands

- CHANGELOG.md
The CHANGELOG for the last two releases was empty, so I updated it with the changes from the commit log.
> Update CHANGELOG for 0.21.3 and 0.21.4

- Cargo.lock
- Cargo.toml
- src/script.rs
I renamed the `sha1` crate used here to `sha1_smol`. `sha1` now refers to a different and much heavier implementation.
See also https://github.com/mitsuhiko/sha1-smol/issues/42
> Switch from sha1 to sha1_smol

- src/cmd.rs
Fixed small typo in src/cmd.rs.
> Fixed small typo

- src/acl.rs
All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/
> chore: remove git.io

- src/cluster.rs
- src/cluster_client.rs
- tests/support/cluster.rs
- tests/test_cluster.rs
> Add username to ClusterClient and ClusterConnection

- tests/test_basic.rs
https://github.com/redis-rs/redis-rs/pull/608 changes the `iter` behavior makes these wrong assumed types now causing tests to fail.
The correct return type for HSCAN is (String, usize) as the field name is returned along the value of that field.
> Fix return type of iter in test_filtered_scanning

- Cargo.toml
I hope this is correct. I had issues when building with the following command line:
```
RUSTFLAGS="$RUSTFLAGS -D unused-crate-dependencies" cargo build
```
> Make async_trait dependency optional

- src/types.rs
- tests/test_basic.rs
Thanks to @doyshinda for pointing this out in #585.
Fixes #587.
> Return errors from parsing inner items

- src/connection.rs
Remove the unnecessary import of `std::ops::Deref` which was triggering a clippy lint because access to the `.deref` method is already covered by the import of `std::ops::DerefMut`.
> remove unused import of `Deref` since already covered by `DerefMut`

- src/commands.rs
- src/lib.rs
- src/types.rs
- tests/test_basic.rs
This PR adds the following commands:
1. [GETEX](https://redis.io/commands/getex) (Available since 6.2.0)
2. [GETDEL](https://redis.io/commands/getdel) (Available since 6.2.0)
Closes #485
> Feat: GETEX and GETDEL Added

- src/commands.rs
- tests/test_basic.rs
ENCODING, IDLETIME, FREQ, REFCOUNT
closes: #599
> add object commands

- src/script.rs
- tests/test_async.rs
- tests/test_async_async_std.rs
- tests/test_basic.rs
Hi there
This PR exposes a load function to not do it manually.
It also changes a repeat logic in sync version of `Script::invoke` to limit the repeat cycle to 2 attempts (The same way as is done in async version).
Take care.
> Add Script::load function

- src/aio.rs
- src/client.rs
- src/cluster.rs
- src/cluster_pipeline.rs
- src/lib.rs
- tests/test_async.rs
- tests/test_async_async_std.rs
While working on https://github.com/redis-rs/redis-rs/pull/641, I ran into warnings executing `make docs` and `make lint` that weren't related to my PR; thought I would make another PR so that others wouldn't run into this when running these commands.
It seems like CI passes in spite of these warnings. I'm not an expert at GitHub workflows and didn't see anything wrong with how things are set up. Maybe something's wrong on my side? Currently running `rustc 1.61.0 (fe5b13d68 2022-05-18)`.
> `make docs` and `make lint` warning fixes

- benches/bench_cluster.rs
- src/cluster.rs
- src/cluster_client.rs
- src/cluster_routing.rs
- src/commands.rs
- tests/test_cluster.rs
Currently, all cluster commands in readonly mode first go to the replica & then in case of errors, they're redirected to the primary.
Instead of the unnecessary replica call & then creating a connection, we can check if a command is readonly or not & then set it to the appropriate node.
This results in a benchmark improvement of ~80% for write commands in readonly mode.
IMO, the option should be renamed from `readonly` to `read_from_replicas`, but that would create a breaking change.
> Cluster: Create read_from_replicas option

- redis/src/commands.rs
- redis/tests/test_basic.rs
Resolves https://github.com/redis-rs/redis-rs/issues/634
Let me know if there's a preferred way to adding WEIGHTS functionality (or anything else that needs to be added or changed!). I contemplated modifying the existing `zinterstore` and `zunionstore` functions, but realized that I would have to make a change to `ToRedisArgs` if I wanted to add this functionality while maintaining the  same parameters.
> add support for weights in zunionstore and zinterstore

- redis/src/aio.rs
Resolves #649 
This allows the usage of `#[instrument]` when using the `tracing` crate.
All generics of Pipeline used in MultiplexedConnection impl Debug this is why I've added an impl of Pipeline only when all of them also impl Debug:
```rust
pub struct MultiplexedConnection {
pipeline: Pipeline<Vec<u8>, Value, RedisError>,
db: i64,
}
```
cc @djc
> impl Debug for MultiplexedConnection & Pipeline

- .github/workflows/rust.yml
- redis/Cargo.toml
Bumping as the latest version of async-global-executor has bumped its MSRV
> bump MSRV to 1.59.0

- redis/src/cluster.rs
- redis/src/cluster_client.rs
- redis/src/cluster_pipeline.rs
- redis/tests/support/cluster.rs
Most of the crates in the Rust ecosystem use `builder()` & `build()` for client & builder as well as `new()` for both of them. Currently, the redis crate uses the unintuitive `open()` methods for the same.
With this PR, I've changed the cluster client to follow the proper builder pattern and redirect the old methods to the new ones.
Also refactored the cluster client in 2 main ways:
- Moved the `build()` method from the client to the builder & made it public
- Create a crate-level struct `ClusterParams` to hold all the params inside a single struct instead of multiple fields in the main struct
- This struct will be used in the later PRs to pass cluster params to & inside the ClusterConnection impl
In addition, improved the documentation as I saw fit.
> [1/5] cluster: implement proper builder pattern & minor refactor

- src/commands.rs
- src/lib.rs
Cherry-picked from the main branch
> Make Direction a public enum to use with Commands like `blmove` (#646)

- redis/src/connection.rs
Connect to ipv6 addr failed because url.host().to_string() got a `[fdbd:dc02:ff:1:1:174:229:45]` String.
Which cannot parse to IPv6Addr: 
https://doc.rust-lang.org/src/std/net/addr.rs.html#963-980
Just use IPv6Addr's to_string() aka Display trait can fix it.
https://doc.rust-lang.org/src/std/net/ip.rs.html#1758-1850
> Support ipv6 connect for #290 #293 #332 #470

- redis/src/acl.rs
Fix bug of unhandled newly defined flags when call `acl_getuser`.
> Add Rule::Other to cover newly defined flags. #682

- redis/src/cluster.rs
- redis/src/commands/mod.rs
- redis/src/types.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
On rust 1.65.0, main branch of redis-rs can not pass lint workflow.
Solved issues is
- explicit-auto-deref
- bool-to-int-with-if
- needless-borrow
> fix: solve lint issues

- redis/src/cluster.rs
- redis/src/cluster_client.rs
- cluster: change orders of declarations
- cluster_client: add `Self::`
- no public api is changed
- cluster: implementation is not changed only order of declarations is changed
- cluster_client: add `Self::` it should do not change behavior
- this PR is depends on https://github.com/redis-rs/redis-rs/pull/705
- you can check actual file changes on https://github.com/0xWOF/redis-rs/pull/14
> [2/5] [2] cluster, cluster_client: minor refactorings (change order of code, use Self)

- redis/src/aio.rs
- redis/tests/test_async.rs
Improve MultiplexedConnection Error Handling
It was recently discovered that `aio::MultiplexedConnection`
does not properly handle errors. If a command in the pipe fails,
responses from subsequent commands in the pipe are not processed
and will be returned to the next request issued on the connection,
with potentially catastrophic results. This fix ensures that
all pending commands in the pipe are processed before returning.
Fixes #698.
> Improve MultiplexedConnection Error Handling

- redis/src/cluster.rs
- cluster: move connect function to ClusterConnection impl
- cluster: follow up usage code of connect function
- cluster:
- no public api is changed
- code is changed but behavior will not be changed
- this PR is depends on https://github.com/redis-rs/redis-rs/pull/706
- you can check actual file changes on https://github.com/0xWOF/redis-rs/pull/15
> [2/5] [3] cluster: move connect to main impl

- redis/tests/test_basic.rs
- assert result of `con.object_idletime` with equal or less than 1 instead of equal with 0
- Result of `con.object_idletime` is affected by machine. So test is failed intermittently.
- if `con.object_idletime` has bug that return 1 when real value is 0, then this is can't catch the bug.
closes #713
> fix(test/basic): assert result of con.object_idletime with equal or less than 1

- redis/src/cluster.rs
- cluster: move ClusterConnection struct declaration to above of impl
- cluster: move set_auto_reconnect
- cluster:
- no public api is changed
- code is changed but behavior will not be changed
- this PR is depends on https://github.com/redis-rs/redis-rs/pull/707
- you can check actual file changes on https://github.com/0xWOF/redis-rs/pull/16
> [2/5] [4] cluster: change order of codes

- redis/src/cluster.rs
- cluster
- make create_initial_connections as method
- call refresh_slots in create_initial_connections
- cluster:
- no public api is changed
- no behavior is changed
- usage of create_initial_connections is changed
> [2/5] [5] cluster: make create_initial_connections as method, call refresh_slots in create_initial_connections

- redis/src/script.rs
- redis/tests/test_async.rs
- redis/tests/test_async_async_std.rs
This PR adds the `Script::invoke_async` method and corresponding tests.
The aim is to have an asynchronous equivalent to the synchronous `Script::invoke` method.
> Add `Script::invoke_async` method

- redis/src/aio.rs
> Use async-std's name resolution when necessary

- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
https://github.com/redis-rs/redis-rs/issues/727
> Explicit MGET support 

- redis-test/src/lib.rs
`redis-test`  is a convenient tool to write UT, but the correct way to write mock responses for some cases is not obvious.
This PR contains a test case about `pipeline` with `atomic`.
This test case may help people find that they should use `Value::Bulk` as a mock response to test the pipeline with atomic instead of a plain `vec`.
> add test case for atomic pipeline

- redis/src/types.rs
- redis/tests/test_types.rs
This is adding the std::collections::HashMap as a ToRedisArgs so that now would be possible to run HSET commands using a simple HashMap (as it already supports for BTreeMap)
Fixes #444.
> Add hashmap to redis args

- README.md
- redis/CHANGELOG.md
- redis/Cargo.toml
- redis/src/cluster.rs
Reverts breaking change made in 85e92c8ce8c24fc9dd057f39e48304a263e902d3.
Cannot be deprecated since it shares it's name with the trait method and the inherent method will always be preferred.
`doc(hidden)` as a somewhat opinionated addition
> Restore inherent `ClusterConnection::check_connection` method

- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_cluster.rs
The goal is to strengthen tests of authentication
by ensuring that auth is actually required during
the test run, else the test could inadvertently pass 
if credentials aren't actually passed for some reason.
Also factor out some repeated test code into common method.
> Allow disabling `default` user in tests

- redis/src/cluster.rs
- redis/src/cluster_client.rs
- redis/src/connection.rs
- cluster
- rename tls to tls_mode
- make ClusterConnection use same tls_mode on every connections
- determine tls_mode from ClusterParams
- cluster_client
- add tls_mode to ClusterParams
- add tls_mode to builder
- connection
- add comment
- cluster:
- ClusterConnection do not use other tls_mode for each connections any more.
- cluster_client
- ** public api is changed **
- user can determine tls_mode of ClusterConnection from builder
- when user do not specify tls_mode, tls_mode is determined from first item of initial_nodes
- connection
- no public api and binary is changed
> [2/5] [7] cluster: make ClusterConnection use same tls_mode on every connections using ClusterParams

- .github/workflows/rust.yml
- Makefile
- redis/Cargo.toml
- redis/tests/test_module_json.rs
Fixing a couple things to avoid an unnecessary MSRV bump. 
Commit 1:
Fix broken json-module tests
Tests were broken and not actually running due to missing test
dependency. This PR:
* Adds the missing test dependency to the `json` feature
* Reorganizes json tests into separate `test-module` command
and renames tests accordingly. The goal is to not have to
have separate redis modules in order to run core tests.
Commit 2:
Upgrade criterion
This has the side-effect of avoiding the need for
an MSRV bump b/c the criterion crate's `csv` dependency,
which is now optional in 0.4 and in any case not needed by
redis-rs.
> Fix json-module tests and CI

- Makefile
- redis/Cargo.toml
- redis/src/aio.rs
- redis/src/aio/tokio.rs
- redis/src/cluster_async/mod.rs
- redis/tests/test_cluster_async.rs
Furthermore, add additional test run that ensures
async-std tests pass when no tokio features are
enabled.
> Support `async-std` in cluster_async module

- Makefile
- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
[Cluster slot parse refactor](https://github.com/redis-rs/redis-rs/pull/793/commits/ee249465a6fdebaf4276c72437f633dcf24c8ab0)
* Rename `get_slots` to `parse_slots`
* Make a pure function so it can be called in async code as well
* Common `slot_cmd` function
[Common slot parsing](https://github.com/redis-rs/redis-rs/pull/793/commits/870bf25dec80c7f3742881f44d7c3fd3305b5ab5)
Use common `parse_slots` command; this allows for eliminating
a lot of largely duplicate code in the cluster-async module but
requires adding support for `ClusterParams` to track connection
settings for TlsMode, username, password, etc., which was previously
(incompletely) tracked by the connection strings constituting the keys
of the ConnectionMap.
These changes also have the effect of enabling support in the cluster- …
> `cluster-async` common slot parsing

- redis/src/cluster.rs
This function is unable to parse ipv6 hosts due to expecting <host:port> format. Fixed by using rsplit instead which may also be a bit faster.
> cluster: fix parsing ipv6 cluster nodes

- redis/tests/support/cluster.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
Remove some noisy logs, attempt to fix flaky test 
with `atomic` instead of `Cell`.
> Test cleanup

- redis/Cargo.toml
- redis/tests/test_cluster_async.rs
* Stop burying errors in async failover test code
* Remove proptest -- it was only testing failover, which
is already covered by another test. It's not clear to me
that testing failover repeatedly in a proptest context
is that valuable, and the test is extremely flaky in CI.
> Refactor tests

- redis/src/aio.rs
Since the `async` keyword can't be used in traits, the ConnectionLike trait requires that the returned futures be boxed. This is necessary for the trait, but not for usage of the concrete connections. This change allows users to use the core logic without boxing the futures, thus reducing allocations. For example, the ConnectionManager now uses MultiplexedConnection's `send_packed_command`, thus removing the unnecessary boxing and according to DHAT, reducing allocations by half.
> Expose more efficient async interfaces.

- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
Some commands needlessly restricted users by requiring passed arguments to have the same type for redis keys.
closes #125
> feat(commands): introduce new generic for each key arg

- redis/Cargo.toml
- redis/src/types.rs
This also removes an explicit dependency on `webpki` (or `rustls-webpki`), since `RootCertStore::add` raises a `rustls::Error` instead of `webpki::Error`.
> Update Rustls to v0.21.0

- redis/src/cmd.rs
This allows us to allocate memory once, instead of regrowing when arguments are added.
> Allow creating Cmd with capacity.

- README.md
- redis/src/commands/json.rs
- redis/src/lib.rs
- redis/src/types.rs
This is made in reference of [#740](https://github.com/redis-rs/redis-rs/issues/740#issuecomment-1409925147).
The crate [redis-macros](https://github.com/daniel7grant/redis-macros/) adds derive macros for `FromRedisValue` and `ToRedisArgs`, as well as a wrapper type `Json` to unwrap RedisJSON command results. I added suggestions for users to use these macros at several places in the documentation where types were mentioned. I fixed the documentation code blocks in `JsonCommands`, and added more information about RedisJSON results, and how to unwrap it with `Json`.
Feel free to edit if you find any inaccuracies.
> Improve documentation, add references to redis-macros

- redis/src/connection.rs
- redis/src/types.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
This change adds the error's kind to the string representation of the error. So the error that was
`An error was signalled by the server: 10279 127.0.0.1:39192` 
will now be
`An error was signalled by the server - Moved: 10279 127.0.0.1:39192` 
which makes the error much clearer.
> Improve error logging.

- .github/workflows/rust.yml
- redis-test/Cargo.toml
- redis/Cargo.toml
Required by recent release of crate `base64` version 0.21.1
> Bump MSRV to 1.60

- redis/src/cmd.rs
newer Rust versions warn of a variable, that is unnecessarily mut
Just removed the `mut`
> fix: unnecessarily mutable variable

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/src/types.rs
- redis/tests/support/mock_cluster.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
This make some changes to how errors are handled in the redis cluster clients, most notably:
* Remove exclusions -- in practice, exclusions create a lot of unnecessary connection rebuilding/slot refreshes when a failed command results in a `MOVED` error.
* Attempt to refresh failed connections when IO errors occur instead of adding exclusions and ultimately refreshing slots due to the above-described scenario
* Only retry given a subset of error types, otherwise return error immediately.
> Refactor cluster error handling

- redis/Cargo.toml
- redis/examples/async-connection-loss.rs
- redis/src/aio.rs
- redis/src/client.rs
- redis/src/types.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
This change allows the connection manager to make multiple attempts to reconnect to the server, in case the server is temporarily unavailable during the first reconnect attempt.
> connection_manager: retry and backoff on reconnect

- redis/Cargo.toml
time functions are used here
https://github.com/redis-rs/redis-rs/blob/main/redis/src/cluster_async/mod.rs#L301
> add time feature to tokio dependency

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
This PR adds proper `ASK` redirection for the async cluster implementation, so rather than simply rebuilding slots, which may not be an appropriate response to `ASK` anyway, it issues the relevant `ASKING` command to the redirected node and issues the query.
A `Redirect` enum has been added for better handling of both redirect scenarios.
The async cluster `MOVED` implementation has also been tweaked. Instead of immediately refreshing slots, the redirected node will be queried, and slots will be refreshed after the redirected request has been made. The same approach has not been taken on the sync implementation for now because doing so would require greater refactoring than is appropriate here.
> Improved redirection error handling

- README.md
The current guidelines in the README for testing and development are incorrect for macOS users since we do not have access to `librejson.so`. Instead, macOS users need to link the env variable to `librejson.dylib` which has added to the README along with a link to the Redis JSON repo.
> Amend README for macOS users

- redis/src/cluster_async/mod.rs
- redis/tests/test_cluster_async.rs
If a request's `route` field is set to None and the request was redirected, it should go to the redirected address regardless of the original route. Currently it goes to a random node.
> Fix redirect routing on request with no route.

- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
This change allows us to send the internal state of the client to async functions without the `self` reference imposing a lifetime.
> cluster_async: Wrap internal state with Arc.

- redis/src/cluster_async/mod.rs
Currently every request is prepended with a PING, and is only sent when the ping completes. This slows down performance significantly - removing this increased TPS on my test machine by 50%.
> Remove connection checking on every request.

- redis/src/aio/connection.rs
> Fix async connect when ns resolved to multi ip

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_client.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
This change allows the user to configure the wait duration between retry
attempts in the cluster clients. The change doesn't the current wait time,
but it does contain a fix to the tests, which will allow us to reduce the defaults
without breaking the tests.
This change also introduces jitter, so that if multiple requests
are waiting, they won't be all sent at exactly the same time.
> Allow configuration of cluster retry wait duration

- redis/src/cluster_async/mod.rs
This change reverts most of the performance degradation introduced recently. Using [this benchmark](https://github.com/nihohit/redis_benchmark) I measured ~320K TPS on version 0.23, ~160K TPS on main, and ~295K TPS after this change.
The cause of the degradation seems to be that existing connections, which were received on the happy path, were wrapped 4 times - 2 boxes, 2 shares. Maybe more, if the compiler had to move the connection to heap for the boxed/shared generator. This change removes all of these unnecessary allocations.
> Improve async cluster client performance.

- .github/workflows/rust.yml
Not sure if this ever worked properly. Cache action was unable to access the redis binaries, and furthermore the binaries were not cached by redis version.
> CI: Fix redis caching

- redis/src/cluster_async/mod.rs
The issue that required the random connection was that we couldn't hold the read lock across an await point, because then the client might start working on a refresh slots/connections operation, try to take the write lock, and a deadlock would be created, because the client stopped working on the requests. 
This PR solves the issue by retaking the lock at a later point, where a random connection can be taken without yielding at an await point.
> Move random connection creation to when needed.

- redis-test/Cargo.toml
Apparently needed to get criterion-compare action working; should be harmless in any case
> Exclude bench from test crate

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/tests/support/mock_cluster.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
Commands that should be routed to all nodes or all masters will now be routed correctly.
This Pr includes:
1. https://github.com/redis-rs/redis-rs/pull/842, in order to maintain consistent behavior between cluster clients.
2. Moved the `Route` struct into `RoutingInfo` as the `SpecificNode` variant, instead of the `ReplicaSlot`/`MasterSlot` variants. This was done because the current `RoutingInfo`->`Route` mapping functions lost information from `RoutingInfo` in variants that don't map to a specific route.
3. Instead of returning a `(String, RedisResult<Response>)`, cluster_async operations now return `(OperationTarget, RedisResult<Response>)`, where operation target disambiguates single node operations from fan-out operations. This is required, since fan-out operations can't return a …
> Support fan-out commands in cluster-async

- redis/Cargo.toml
- redis/src/aio/async_std.rs
- redis/src/aio/tokio.rs
- redis/src/connection.rs
- redis/src/lib.rs
This enables keep alive on tcp sockets via `keep-alive` feature
~Do you want to have it configurable so that only `ConnectionManager` would enable it?
There is no harm in enabling it for short living connections as default intervals are quite long~
Note that this doesn't really fix anything, but for long living connections it will speed up failure detection
Related to #885
> package `socket2 v0.5.3` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.60.0
Unfortunate sad state of rust networking
Just for reference redis(server) default value for keep-alive is 300 seconds ([Ref](https://raw.githubusercontent.com/redis/redis/7.0/redis.conf))
> Enable keep alive on tcp connections via feature

- redis/src/cluster_routing.rs
- redis/src/commands/mod.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
The choices were based on the request_policy tip from the COMMAND output.
> Update routing data for commands.

- redis/Cargo.toml
Trying to avoid bumping MSRV to 1.63 just for a
dev dependency.
> Pin `tempfile` dependency

- redis/Cargo.toml
- redis/src/cluster.rs
- redis/src/cluster_client.rs
- redis/src/connection.rs
- redis/src/lib.rs
- redis/src/sentinel.rs
- redis/src/types.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
- redis/tests/support/sentinel.rs
- redis/tests/test_sentinel.rs
Hi! I've created this implementation of some Redis Sentinel logic, which I think would be a nice addition to this crate. I'm going to need something like this anyway for my projects, so I've decided to try and contribute it here first.
This is my first Rust open-source contribution, and I have very little Rust experience, so if anything seems weird please enlighten me!
Before doing this, I've seen that there are two issues about adding sentinel support:
https://github.com/redis-rs/redis-rs/issues/539
https://github.com/redis-rs/redis-rs/issues/703
And two attempts to implement this, one in a fork, and one in a separate crate:
https://github.com/redis-rs/redis-rs/compare/main...doyshinda:redis-rs:sentinel
https://github.com/aljazerzen/redis-sentinel-rs/blob/main/src/client.rs
Both are …
> Add basic Sentinel functionality

- redis/tests/support/cluster.rs
It is now required that the cluster creation waits for all servers to change their state to OK before it returns, rather than waiting only for the first one to change its state.
This change prevents flaky tests due to CLUSTER DOWN errors by not starting testing before all servers are ready.
> Changed cluster creation to wait for all servers to change their state to OK

- redis/tests/support/sentinel.rs
- redis/tests/test_sentinel.rs
This caused panics when the node was in the wrong state.
> Remove tuple casting on command result.

- redis/Cargo.toml
- redis/src/connection.rs
https://github.com/rustls/rustls/pull/1383
Fixes this linter error:
https://github.com/redis-rs/redis-rs/actions/runs/5737543101/job/15699563878?pr=918
> Rustls: Remove usage of deprecated method.

- .github/workflows/rust.yml
This adds ~10 minutes to previous test run time, in order to leave a comfortable margin, while still significantly reducing the run time of the task in case it gets stuck. Without defining this, the task runs for 6 hours.
> add timeouts to tests github action.

- README.md
The extern crate statement used to be an important part of rust, several years ago.
These days it's a point of confusion for newcomers without adding any value, and should be omitted.
> Remove redundancy from example

- redis/tests/test_module_json.rs
The test was broken by version 1.0.105 of serde_json, due to https://github.com/serde-rs/json/pull/1055 .
> Fix JSON serialization error test.

- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/src/parser.rs
- redis/src/types.rs
- redis/tests/test_cluster_async.rs
This change implements the response_policy tip in the async cluster.
https://redis.io/docs/reference/command-tips/#response_policy
This means that the results from fan-out commands will be aggregated
differently, based on the sent command.
> async cluster: Group responses by response_policy. 

- redis-test/Cargo.toml
Since `redis` is found by path, there's only a single version to choose.
> Remove redis version from redis-test.

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/tests/test_cluster_async.rs
This PR is based over https://github.com/redis-rs/redis-rs/pull/888 .
This allows the async cluster client to split keyed commands so that
keys will be grouped by the slot they belong in, and sent only to the
relevant shard.
> Add support for multi-shard commands.

- redis/examples/async-connection-loss.rs
- redis/src/client.rs
as per the request here:
https://github.com/redis-rs/redis-rs/issues/737
> Deprecate functions that erroneously use `tokio` in their name.

- redis/src/aio/connection.rs
- redis/src/aio/mod.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/connection.rs
CLIENT SETINFO is a new command to Redis 7.2.0.
> Call CLIENT SETINFO on new connections.

- redis/tests/support/cluster.rs
This might help us understand the flakyness in the cluster tests.
> Log cluster creation output in tests.

- Makefile
Apparently there's some hidden race condition between the tests. Locally
this prevented crashes.
> Run module tests sequentially. 

- redis/Cargo.toml
- redis/src/aio/async_std.rs
- redis/src/aio/tokio.rs
- redis/src/connection.rs
`TCP_NODELAY` is quite important for redis client because this greatly affects latency.
This PR adds this option by default.
This PR also implements writev for tokio tcp connection (maybe for future optimization).
Fixes #354 .
> feat(redis): set TCP_NODELAY to reduce latency

- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/src/lib.rs
- redis/tests/test_cluster_async.rs
This PR is based over https://github.com/redis-rs/redis-rs/pull/900 .
This change allows the user to specify routing information for commands. This is especially helpful for commands that don't have an explicit request policy, such as BGSAVE, and so are sent to a random node.
> Allow passing routing information to cluster.

- redis/src/pipeline.rs
This pr optimize the `make_pipeline_results` method by pre-allocating memory for rv.
> feat: optimize make_pipeline_results by pre-allocate memory

- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
Hello,
The feature has been requested in #944 & #476.
The commands implemented are:
https://redis.io/commands/bzpopmin
https://redis.io/commands/bzpopmax
https://redis.io/commands/bzmpop
Tests were added for all 3 of them.
> Sorted set blocking commands

- redis/src/cluster_async/mod.rs
- redis/tests/test_cluster_async.rs
rebased over https://github.com/redis-rs/redis-rs/pull/899 .
This means multi node operations now get error handling, and can trigger
MOVED, etc.
Additionally, func was removed from CmdArg::Cmd/Pipeline. This removes
the need to allocate a box on every request, and slightly reduces code
complexity.
> Execute multi-node requests using try_request.

- .github/workflows/rust.yml
This happens due to a consistent crash -
https://github.com/RedisJSON/RedisJSON/issues/1124
> Disable JSON module tests for redis 6.2.4.

- .github/workflows/rust.yml
- redis-test/Cargo.toml
- redis/Cargo.toml
It's required by regex v1.10.2.
https://github.com/redis-rs/redis-rs/actions/runs/6760188489/job/18373652560?pr=981
> Update minimal rust version to 1.6.5

- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
Changing timeout values of functions:
- blmove
- blmpop
- blpop
- brpop
- brpoplpush
- bzpopmax
- bzpopmin
- bzmpop_max
- bzmpop_min
The reason behind it is that the timeout is in seconds and being limited to a minimum of one second is challenging.
The timeout value of all of these functions is a double value in redis versions greater than 6.0.0.
> Changing timeouts from usize and isize to f64

- redis/src/cluster_client.rs
So, here's the deal – right now, when you want to initialize a `ClusterClient`, you're kinda stuck with using a `Vec` data type. This works fine for a lot of situations, but this restricts users options and fails to provide the flexibility they desire. It. This limitation can force you into making extra allocations or unneeded conversions, and nobody wants that.
But hey, good news! Here's a solution for it. This PR changes the `ClusterClientBuilder::new`, `ClusterClient::new`, and `ClusterClient::builder` signatures. The trick is – they can now accept any data type that's got the `IntoIterator` trait going for it. 
It means you can initialize a `ClusterClient` with a bunch of different data types. This gives you the freedom to keep things flexible and make your life easier.
This update …
> Accept iterator at `ClusterClient` initialization

- redis/src/cluster_async/mod.rs
This change will cause transactions with commands that are routed to replicas and primaries to prefer the primary routing over the replica.
> Prefer routing to primary in a transaction.

- redis/src/connection.rs
- redis/tests/test_basic.rs
When sending subscibre/unsubscribe messages to the server, the pub/sub client might receive messages that it can mistake to be the response, and not return to the next `get_message` call. This fix ensures that pub/sub messages will be queued until the next
`get_message` call, so that no message will be missed.
> Sync Pub/Sub - cache received pub/sub messages.

- redis/src/cluster.rs
- redis/tests/support/mock_cluster.rs
- redis/tests/test_cluster.rs
The leading MULTI prevents the transaction from being properly routed, because there's no routing for the multi command, and the routing check doesn't iterate through the contained commands. In order to route the request correctly, we drop the leading MULTI from the routable.
> Fix sync cluster behavior with transactions.

- redis/tests/support/cluster.rs
Add retries to both the server and cluster creation process. I believe the core
fix here is just adding a sleep after the server child process is spawned, however
I'm leaving the retries in as I don't think they hurt anything.
> Tests: Add retries to test cluster creation

- redis-test/Cargo.toml
Publishing to crates.io without the version specification 
is currently not possible. Reverting these changes for now 
until we have a better solution/workaround.
> Revert redis-test versioning changes

- redis/Cargo.toml
- redis/src/types.rs
This is a breaking change, bumping the `ahash` dependency in a semver-incompatible way
> Bump aHash to v0.8.6

- redis/src/commands/mod.rs
This change updates expiration values provided to some commands in the `Command` trait to be of type `i64` or `u64` where appropriate, replacing the previously used `usize` type.
More specifically, the commands that are updated are
- SETEX, PSETEX
- Expiration value changed from `usize` to `u64`
- EXPIRE, PEXPIRE, EXPIREAT, PEXPIREAT
- Expiration value changed from `usize` to `i64`
For the `*SETEX` commands, there is no mention of supporting negative values. And indeed, providing a negative value through redis-cli returns an error message.
For the `*EXPIRE*` commands, I couldn't find the paragraph in the docs referenced in #575, nor any other mention that the commands accept a negative expiration argument. However, in testing with redis-cli it seems a negative expiration value is valid …
> Update Command expiration values to be an appropriate type

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_client.rs
Moved `tls_params` into `ClusterParams`, and made the sync cluster use `ClusterParams` directly instead of copying its fields.
> Order in usage of ClusterParams.

- redis/tests/support/cluster.rs
Check to make sure the port is open/accessible from the redis 
server process before moving onto the cluster creation process.
Recent testing suggests that initiating cluster creation before the
server process has a chance to fully initialize is the biggest cause
of flaky cluster tests, so testing the port prior should prevent that.
> Tests: Reduce cluster setup flakiness

- redis/src/types.rs
- redis/tests/test_types.rs
When the list in a bulk value contains an odd number of elements, the last element would be silently discarded by MapIter. The list is now checked to be of even lenth during initialization.
> Fix HashMap conversion (#977)

- redis-test/Cargo.toml
- redis/Cargo.toml
- redis/src/aio/connection_manager.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/client.rs
- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_client.rs
- redis/tests/support/mock_cluster.rs
- redis/tests/test_async.rs
- redis/tests/test_cluster_async.rs
This allows the users to define a connection timeout to the async cluster, which will cause the `refresh_slots` action to timeout if it takes too long to connect to a node.
> Add connection timeout to the cluster client

- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
Hello
I have just found that the command SMISMEMBERS is missing from the lib.
I think it can be great for checking presence of multiple members with one network connection.
As I didn't found a Contributing section, I'm naively proposing this change.
Please do not hesitate to tell me what changes are needed along with my initial commit.
Please note that SMISMEMBERS appears at redis version 6.2.0
> feat: add SMISMEMBER command

- redis/src/cluster_routing.rs
Instead of allocating the ASCII uppercase conversion of `self.arg_idx(1)` and then copying it into the target vec, we copy the slice, and then convert it to uppercase in-place. This saves the allocation of the vec, which is only used for copying.
The perf difference here is too small to be conclusive in benchmarks, but the reduction in the generated assembly is noticable (~920 lines of assembly to ~800) - https://godbolt.org/z/7srEv8vra
> Remove allocation from `command` function.

- Makefile
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_async_async_std.rs
ATM Tokio's runtimes hide panics from spawned tasks, and continue running. This PR ensures that we'll be catch panics even if they're thrown in spawned tasks.
> Catch panics from task::spawn in tests.

- Makefile
- redis/src/aio/connection.rs
- redis/src/aio/mod.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/cluster.rs
- redis/src/cluster_client.rs
- redis/src/connection.rs
- redis/src/lib.rs
- redis/src/types.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_basic.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
- redis/tests/test_module_json.rs
Since there's a discussion starting about what might become RESP4 (https://github.com/redis/redis/issues/12873), this
PR will make it easier to add more RESP versions in the future.
> Use enum instead of boolean for RESP version.

- redis/src/aio/multiplexed_connection.rs
Instead of using a Vec<Value> and allocating / popping values from it,
single requests will now create only a single Value object, which will
reduce the heap usage for single requests.
This gives us a small but consistent perf improvement of about 1% in my single threaded benchmarks, slightly higher in multithreaded benchmarks.
> MultiplexedConnection: Remove unnecessary allocation in send.

- Makefile
- redis/src/aio/async_std.rs
- redis/src/cluster_async/mod.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
- redis/tests/test_bignum.rs
- redis/tests/test_cluster_async.rs
Added `RUSTFLAGS="-D warnings" ` to all CI flows, to ensure that warnings won't appear when only some features are used, since our lint flow checks for all features at once.
> Fix warnings that appear only with native-TLS.

- redis/src/commands/json.rs
docs have 
assert_eq!(redis::cmd("GET").arg("my_key").arg("$").query_async(&mut con).await, Ok(String::from(r#"[{"item":42}]"#)));
should be 
assert_eq!(redis::cmd("JSON.GET").arg("my_key").arg("$").query_async(&mut con).await, Ok(String::from(r#"[{"item":42}]"#)));
> Fix documentaion error

- redis/examples/async-await.rs
- redis/examples/async-connection-loss.rs
- redis/examples/async-pub-sub.rs
- redis/examples/async-scan.rs
- redis/src/aio/connection.rs
- redis/src/client.rs
- redis/src/sentinel.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
`aio::Connection` is deprecated due to it entering erroneous state when user drops its futures before they complete (similar to OpenAI's [RedisPy issue](https://openai.com/blog/march-20-chatgpt-outage)). `PubSub` & `Monitor`, which are built on top of `aio::Connection`, are now exposed for direct creation from a `client`, in order to allow us to transition their implementation to another backing connection.
> Deprecate `aio::Connection`

- redis/src/aio/mod.rs
- redis/src/connection.rs
`req_packed_commands` is meant for internal usage by the `Pipeline` object, and is an easy to misuse footgun.
See https://github.com/redis-rs/redis-rs/issues/1017#issuecomment-1878158571
> Hide the `req_packed_commands` from docs.

- redis/src/commands/json.rs
In the json_get method documentation, changing is to if to correct the grammar of the sentence.
> Fixes minor grammar mistake in json.rs file 

- redis/Cargo.toml
- redis/src/aio/mod.rs
- redis/src/connection.rs
> feat: add disable client setinfo feature and its default mode is off

- redis/src/aio/connection.rs
- redis/src/cluster_pipeline.rs
- redis/src/cmd.rs
- redis/src/connection.rs
- redis/src/lib.rs
- redis/src/pipeline.rs
- redis/src/types.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mock_cluster.rs
- redis/tests/test_types.rs
This PR adds new methods, `from_owned_redis_value` and `from_owned_redis_values` to complement the existing `from_redis_value` and `from_redis_values`.
A typical call to `FromRedisValue::from_redis_value()` looked like:
```rs
let res: (Vec<u8>, (), isize) = from_redis_value(&self.read_response().await?)?;
```
This call-site is typical, in that we produce a temporary (`self.read_response().await?`) and then pass a reference to that temporary.
This means that even if we want to just "take" the data stored in the `redis::Value`, we are forced to clone it, including any reallocations. For example, if I want to get out a `Vec<u8>`, but the value is a `redis::Value::Data(Vec<u8>)`, I have to copy the slice into a new vector instead of just returning it as-is.
---
Slightly abbreviated, the …
> Add `FromRedisValue::from_owned_redis_value` to reduce copies while parsing responses

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
This PR refactors the cluster `SlotMap` to account for 4 existing issues:
1. ATM clusters can't be created with partial slot coverage. This is erroneous, because given the right configuration the Redis cluster can work in such a situation, so we shouldn't fail it.
This was fixed by removing the asserts enforcing this from the cluster connections, and adding to the SlotMap the start slot of each range, so that it could return `None` when trying to get the address for a missing slot.
2. Since SlotAddrs saves at most 1 replica (or none, if
`read_from_replica` is false), it means that when there are 2 or more
replicas in the cluster, `AllNodes` commands aren't actually sent to
all nodes.
This was fixed by saving a Vec of addresses in SlotAddrs instead of a single replica.
3. …
> Cluster: fix read from replica & missing slots.

- redis/src/aio/mod.rs
This ensures that generated rustdoc for `ConnectionManager` will mention that the `connection-manager` feature is required to expose it.
This was done previously in #475, but seems to have been lost in refactor in #821.
> docs: add "connection-manager" cfg attr

- redis/src/cmd.rs
- redis/src/sentinel.rs
- redis/tests/support/sentinel.rs
Replace Vec reference with a slice, and remove iterator trait when using ExactSizeIterator, since it encompasses it.
> Fix new clippy lints.

- redis-test/src/lib.rs
- redis/CHANGELOG.md
- redis/benches/bench_basic.rs
- redis/examples/streams.rs
- redis/src/acl.rs
- redis/src/cluster.rs
- redis/src/cluster_pipeline.rs
- redis/src/cluster_routing.rs
- redis/src/connection.rs
- redis/src/geo.rs
- redis/src/parser.rs
- redis/src/pipeline.rs
- redis/src/push_manager.rs
- redis/src/streams.rs
- redis/src/types.rs
- redis/tests/parser.rs
- redis/tests/support/mock_cluster.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_basic.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
- redis/tests/test_module_json.rs
- redis/tests/test_types.rs
See the naming convention here:
https://redis.io/docs/reference/protocol-spec/
> Rename Value enum types in order to match Redis RESP names.

- redis/src/aio/connection_manager.rs
- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/connection.rs
- redis/src/sentinel.rs
- redis/src/types.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
Parsing errors mean that the connection received a response it doesn't know how to handle. This means that it cannot make sense of the next values sent over the connection, and the connection must be replaced.
related:
https://github.com/redis-rs/redis-rs/issues/984#issuecomment-1930956524
> Reconnect on parsing errors.

- redis/src/cluster_async/mod.rs
- redis/tests/test_cluster_async.rs
This change ensures that reconnect attempts that happen during retries, or new connections that happen after MOVED/ASKING errors, will be saved instead of constantly reconnecting until slots are refreshed.
https://github.com/redis-rs/redis-rs/issues/1025
> Save reconnected connections during retries.

- redis/src/aio/multiplexed_connection.rs
- redis/tests/test_async.rs
fix a bug introduced in 70dfb957
> [fix] make `Pipeline` handle returned bulks correctly

- redis/tests/support/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_async_async_std.rs
`aio::Connection` is deprecated, we should test `aio::MultiplexedConnection` instead.
> Remove the usage of aio::Connection in tests.

- redis/src/parser.rs
- redis/src/types.rs
- redis/tests/test_async.rs
Currently server errors stop the parser and return a RedisError. This caused errors that are returned inside an array, such as transaction errors, to cause the rest of the array to not be parsed. 
This is solved by adding an internal value type that includes the server errors, so when parsing to the internal value type, the array will finish parsing, and then extracting the error.
Pros:
- backwards compatible
- allows us to replace the parsing backend (for [redis-protocol](https://crates.io/crates/redis-protocol)?) without affecting the users.
cons:
- repetition - some changes to Value might need to be copied to InternalValue.
- adds some conversion overhead
> Handle server errors in array response.

- redis/src/parser.rs
- redis/src/types.rs
Parsing errors are client-side errors, that are caused by bad output from the server. Response errors are server-side errors, caused by bad input from the user / client. Parse errors cause the client to be in an unrecoverable state. response errors are OK.
> Separate parsing errors from general response errors.

- redis/examples/async-multiplexed.rs
When I first saw it, I thought it could only accept the `&str` type. After tried & read more documents, I found that `String` and `&String` are also acceptable. So I hope this ambiguity can be cleared up.
> Small disambiguity in examples

- redis/Cargo.toml
- redis/src/aio/connection_manager.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/aio/runtime.rs
- redis/src/client.rs
The futures-time crate brings in a bunch of extra dependencies from the async-std ecosystem even when this crate is configured to use `tokio-comp`. Additionally, it hasn't had a release in 2 years, so it depends on older versions of its transitive dependencies (for example, rustix). It is relatively straightforward to replace it with some direct calls to the runtime.
> Avoid library dependency on futures-time

- .github/workflows/rust.yml
- Cargo.lock
- README.md
- redis/CHANGELOG.md
- redis/Cargo.toml
- redis/src/aio/multiplexed_connection.rs
- redis/tests/test_async.rs
https://github.com/redis-rs/redis-rs/issues/1078
This fixes a bug where pipeline responses for a single request that return a `Vec` as that single value aren't wrapped in another `Vec`.
Since this is the second bug introduced by https://github.com/redis-rs/redis-rs/commit/70dfb95713fbcfe944a9262189c2adf23c12977c,
while we still want to maintain the performance improvement for single requests introduced by same, the fix is to separate the logic of single responses from pipeline responses.
> MultiplexedConnection: Separate response handling for pipeline.

- redis/src/client.rs
continuing https://github.com/redis-rs/redis-rs/pull/913
> Deprecate function that erroneously use tokio in its name.

- redis/tests/test_async.rs
- redis/tests/test_basic.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
- redis/tests/test_types.rs
This will allow us to run groups of async tests separately - `cargo test cluster_async` / c`argo test async`, etc.
> Wrap tests with modules.

- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
Commands which have more arguments that aren't keys (such as `CONFIG SET timeout`) shouldn't be routed according to the hash of the additional arguments - so they must be marked explicitly as routed randomly, otherwise the check in `route_for_pipeline` might erroneously mark it as a cross-slot pipeline.
> Route unkeyed commands to a random node.

- redis/src/types.rs
- redis/tests/test_types.rs
With these macros(kudos to serde crate) it will be very easy to add other std types like `Mutex`,`Rc`,`ArcWeak` 
I think this PR might contains breaking changes for some users because from now you need to specify output type. See `test_vec` function.
> feat: add implementation of `ToRedisArgs`,`FromRedisValue` traits for `Arc<T>`,`Box<T>`,`Rc<T>`

- redis/src/cluster_async/mod.rs
attempted fix for https://github.com/redis-rs/redis-rs/issues/1098
> Handle empty results in multi-node operations.

- redis/src/aio/multiplexed_connection.rs
- redis/src/client.rs
If user uses `MultiplexedConnection::new` to create `MultiplexedConnection` without a response timeout, `std::time::Duration::MAX` is used. This would not do any timeout useful in practice.
In our usecase, we choose to do not provide `response_timeout` because we manage timeout ourselves in the upper layer. And during profile, we catch that the underlying `MultiplexedConnection` is also calling timeout which is not necessary.
> Make response_timeout Optional

- redis/benches/bench_cluster.rs
- redis/benches/bench_cluster_async.rs
- redis/tests/support/cluster.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
1. tests with mocks shared the same handle, so they dropped each other's state.
2. tests with real cluster shared the same ports, so the cluster couldn't run concurrently.
> Fix issues that prevented cluster tests from running concurrently.

- redis/src/cluster_async/mod.rs
Since `RoutingInfo` is not an `Option` type, docs should not hint at passing `None` as a parameter
> Update cluster_async router_command docs

- redis/src/connection.rs
Fix compilation error occurs on Windows only. Looks like a mistake IMHO.
```
...
Compiling redis v0.25.0 (C:\GitHub\redis-rs\redis)
error[E0412]: cannot find type `HashMap` in this scope
--> C:\GitHub\redis-rs\redis\src\connection.rs:355:16
|
355 |     let query: HashMap<_, _> = url.query_pairs().collect();
|                ^^^^^^^ not found in this scope
|
help: consider importing one of these items
|
1   + use combine::lib::collections::HashMap;
|
1   + use crate::types::HashMap;
|
1   + use std::collections::HashMap;
|
For more information about this error, try `rustc --explain E0412`.
error: could not compile `redis` (lib) due to previous error
```
> Fix compilation on Windows.

- redis/Cargo.toml
- redis/src/commands/mod.rs
- redis/src/lib.rs
- redis/src/script.rs
- redis/tests/test_basic.rs
- redis/tests/test_script.rs
Currently it's not possible to add a script to a pipeline, adds a new method `script` to the pipelines.
I also exposed `eval_cmd` and `load_cmd` in the script invocation.
> Add `invoke_script` to commands to allow for pipelining of scripts

- redis/src/types.rs
> fix #1150: change int types for expiry to `u64`

- redis/src/commands/mod.rs
- redis/tests/test_streams.rs
This adds a new command for the redis XGROUP CREATECONSUMER.
This is one of the missing steam commands described in https://github.com/redis-rs/redis-rs/issues/1153
> Add xgroup_createconsumer command support

- redis/src/cluster_client.rs
For ClusterClientBuilder, if we call tls(TlsMode::Insecure) first, a following certs() call will set builder_params.tls to Some(TlsMode::Secure) 
In this pr, we will check builder_params.tls  before setting it in fn certs()
> check tls mode before setting it in the call of certs()

- redis/src/lib.rs
As per `Cargo.toml`, `aio` is not enabled by default, and `keep-alive` is enabled:
https://github.com/redis-rs/redis-rs/blob/523b4ebe4ca052f97ea3db5b7792601092106397/redis/Cargo.toml#L94
However, the documentation for these flags is incorrect. This pull request fixes this error.
https://github.com/redis-rs/redis-rs/blob/523b4ebe4ca052f97ea3db5b7792601092106397/redis/src/lib.rs#L56
https://github.com/redis-rs/redis-rs/blob/523b4ebe4ca052f97ea3db5b7792601092106397/redis/src/lib.rs#L65
> Correct the document of default feature flags

- redis/src/commands/mod.rs
- redis/src/streams.rs
- redis/tests/test_streams.rs
This adds a new command for the redis XAUTOCLAIM along with a Reply object to parse the response
This is one of the missing steam commands described in #1153
> Add xautoclaim command support

- redis/src/types.rs
- redis/tests/test_types.rs
A RedisError that was created with `ErrorKind::IoError` instead of an actual `io::Error` will now be recognized as an I/O error when checking `is_io_error`. This is required for the correct behavior of `connection_manager`.
https://github.com/redis-rs/redis-rs/issues/1190
> Fix explicit IoError not being recognized.

- redis/src/client.rs
- redis/src/lib.rs
- redis/src/sentinel.rs
- redis/tests/test_sentinel.rs
Add a redis::sentinel::Sentinel::SentinelClient::get_async_connection_with_config that accepts timeouts
I have added just a happy test for calling with long timeouts. I am not versed enough to add a test for actual timeouts but am not sure it is needed since it just ships the parameters on to redis client.
> Timeouts for redis client gotten via sentinel

- redis/src/aio/connection_manager.rs
- redis/src/client.rs
- redis/tests/test_async.rs
Add a redis::aio::ConnectionManager::new_with_backoff_and_timeouts_with_max_delay  Apply a maximum delay. No retry delay will be longer than this `max_delay`.
Todo: I try to add some more cases
> Add max retry delay for every reconnect

- redis/src/types.rs
- redis/tests/test_types.rs
In cases where `T: ToOwned, &T: ToRedisArgs, &T::Owned: ToRedisArgs` we can implement `ToRedisArgs` for `Cow<'_, T>` by delegating to the inner implementations. This gives support for `Cow<[u8]>` and `Cow<str>` out of the box, and allows downstream consumers to get `Cow<Newtype>` implementations for free, without needing to `match` in their code.
An alternative implementation would be to always call `Cow::as_ref`, which would relax the bound of `&T::Owned: ToRedisArgs`, but in cases where the implementation of `ToRedisArgs` is specialized for `&T::Owned` this is suboptimal. As an example, see [`String::as_bytes`][1] vs [`String::as_str`][2] followed by [`str::as_bytes`][3]; by using the specialized implementation of `String::to_redis_args`, we save some overhead.
[1]: …
> Implement `ToRedisArgs` for `std::borrow::Cow`

- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
This allows us to find errors that aren't visible
in stdout/stderr.
> Log the server / cluster logfile on error.

- redis/tests/support/cluster.rs
This PR is based over https://github.com/redis-rs/redis-rs/pull/1200
It solves the issue
```
7531:M 31 May 2024 14:08:24.335 # Warning: Could not create server TCP listening socket 127.0.0.1:44317: bind: Address already in use
7531:M 31 May 2024 14:08:24.335 # Failed listening on port 44317 (TCP), aborting.
```
by switching the cluster's port if cluster creation failed.
> Cluster creation in test: Try getting a new port if the current port isn't available.

- redis/tests/test_async.rs
1. reduced the delay time (not required to fix the test, just to make it run faster.
2. wait after restarting the server, in order to give the connection manager time to reconnect before sending another request. I ran this locally for 500 iterations without failing.
> Fix flakey test.

- redis/src/aio/connection_manager.rs
- redis/src/client.rs
In my code, using the connection_manager, I would like to only set the timeouts but not the back off parameters on creation of the connection_manager. Therefore I suggest to add a new function `new_with_timeouts()` to the connection_manager and subsequently `get_connection_manager_with_timeouts()` to the client.
I also fixed some typos
> Fix some typos in connection_manager.rs and client.rs

- redis/src/aio/multiplexed_connection.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_basic.rs
Fixes https://github.com/redis-rs/redis-rs/issues/1091 for `MultiplexedConnection`.
based over https://github.com/redis-rs/redis-rs/pull/1084
> MultiplexedConnection: Report disconnects without polling.

- redis/src/aio/multiplexed_connection.rs
Introduced by https://github.com/redis-rs/redis-rs/pull/1096 not being rebased over https://github.com/redis-rs/redis-rs/pull/1127 when tested.
> Fix compilation break.

- redis/src/cluster_async/mod.rs
- redis/src/cluster_async/request.rs
- redis/src/cluster_async/routing.rs
This PR doesn't contain any logic or behavior changes, just a code re-organization. It's in preparation for https://github.com/redis-rs/redis-rs/pull/1222#issuecomment-2174995693
> Split `Request` and routing from cluster async to separate files.

- redis/src/aio/connection.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_pipeline.rs
- redis/src/cmd.rs
- redis/src/connection.rs
- redis/src/parser.rs
- redis/src/pipeline.rs
- redis/src/types.rs
- redis/tests/parser.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_basic.rs
1. Remove `InternalValue` and add the `ServerError` variant to `Value`.
2. Don't convert `ServerError`s in the parser to `RedisError`. In order to maintain the behavior of the high level APIs (query/_async), they now call `extract_error`.
3. Used the internal error in order to pipeline connection setup requests - this can remove some back-and-forth with the server, and thus reduce connection setup time.
> Expose Errors in `Value`

- redis/src/aio/connection_manager.rs
- redis/src/aio/mod.rs
- redis/src/aio/multiplexed_connection.rs
- redis/tests/test_async.rs
The last commit of this PR isn't strictly required for the PR, but it improves our test coverage of the connection manager, which is somewhat related.
> Add un/subscribe commands to `aio::ConnectionManager`.

- redis/src/aio/multiplexed_connection.rs
```
--> redis/src/aio/multiplexed_connection.rs:412:79
|
412 | /// even when all clones of the multiplexed connection have been dropped (see https://github.com/redis-rs/redis-rs/issues/1236).
|                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/redis-rs/redis-rs/issues/1236>`
|
= note: bare URLs are not automatically turned into clickable links
= note: `#[warn(rustdoc::bare_urls)]` on by default
```
> Fix documentation warning.

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_async/request.rs
- redis/src/cluster_routing.rs
- redis/src/types.rs
- redis/tests/test_cluster_async.rs
This PR is based over https://github.com/redis-rs/redis-rs/pull/1186
1. Adds a request.rs and routing.rs files to the async cluster connection, in order to move the additional logic outside of the huge mod.rs file.
2. Moves the error handling logic to a seprate function, and add tests for that function.
> Cluster connection - Refactor response handling.

- redis/tests/support/mod.rs
If multiple threads try to set the default provider, the `unwrap` causes a crash, even though we only need one thread to succeed and don't care about failures.
> Fix flakey multi-threaded test runs.

- redis/src/commands/json.rs
- redis/src/commands/mod.rs
- redis/src/geo.rs
- redis/src/types.rs
- redis/tests/test_basic.rs
- redis/tests/test_types.rs
As discussed in https://github.com/redis-rs/redis-rs/pull/1232#discussion_r1648820067, @nihohit proposes to change `is_single_arg` to the length of args to make it possible to retrieve the number of arguments.
The purpose of this PR is to loosen the generic constraints on functions that today require a slice, so that they can take any collection that is convertible to many redis args - for example, a `VecDeque`.
> Change is_single_arg to num_of_args in ToRedisArgs trait

- redis/src/commands/mod.rs
- redis/src/lib.rs
- redis/src/types.rs
- redis/tests/test_basic.rs
Redis 7.4 will support the HASH expired, for commands can refer to: https://redis.io/docs/latest/commands/?group=hash
> Add support of HASH expiration commands

- redis/Cargo.toml
- redis/src/aio/connection_manager.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/client.rs
- redis/src/connection.rs
- redis/src/types.rs
- redis/tests/test_basic.rs
This is done by changing the sync Connection's push sender to the std sender instead of tokio sender.
The decision to use the tokio sender in the sync implementation came from the previous design, where all connections used the same PushManager, and so had to use the same channel type.
https://github.com/redis-rs/redis-rs/pull/898#discussion_r1297473079
based over https://github.com/redis-rs/redis-rs/pull/1251
> Remove tokio dependency from non-aio build.

- .github/workflows/rust.yml
- README.md
- redis/Cargo.toml
removed MSRV from docs, because it is now handled by the `rust-version` field.
affected PRs:
https://github.com/redis-rs/redis-rs/pull/1123
https://github.com/redis-rs/redis-rs/pull/1275
> Bump MSRV to 1.70

- redis/src/streams.rs
- redis/tests/test_streams.rs
This PR adds support for `lag` and `entries-read` values in `XINFO GROUPOS` replies.
It handles missing values, which can happen either because the server cannot determine the values (especially for `lag`) or because the server version does not yet support them.
> Xinfo groups lag and entries-read support

- redis/src/aio/mod.rs
- redis/src/commands/mod.rs
- redis/src/connection.rs
- redis/src/pipeline.rs
- redis/tests/test_async.rs
- redis/tests/test_basic.rs
This change speeds up the setup phase of each new connection, by pipelining all of the commands, instead of sending them one after the other.
> Use pipelines to setup connections

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
Our documentation doesn't specify that the cluster connection reconnects & refreshes topology automatically, which leads to user confusion.
https://github.com/redis-rs/redis-rs/issues/1260
> Improve cluster documentation.

- redis/src/aio/mod.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/aio/pubsub.rs
- redis/src/aio/runtime.rs
- redis/src/client.rs
- redis/src/cluster_async/mod.rs
- redis/src/lib.rs
- redis/src/types.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_basic.rs
This PR adds a new implementation for async pubsub, with the main differences - 
1. The new `PubSub` can be split into a `Sink` and `Stream` structs, so that calls to subscribe / unsubscribe won't prevent the user from listening for messages, due to both `on_message` and `un/subscribe` requiring a mutable reference to the connection.
2. Like the MultiplexedConnection (from which a lot of the its code was copied), it spawns a task that reads & writes from the underlying TCP connection, so that reading from the TCP stream doesn't wait for `await` calls on the user-facing APIs. This is important, because it means the the sink and the stream don't affect each other - if the internal polling waited for some external polling, one of these APIs would've had to wait for the user to `await` the …
> Allow splitting async PubSub to Sink &  Stream.

- redis/src/r2d2.rs
- redis/src/sentinel.rs
- redis/tests/test_sentinel.rs
Hi, I apologize beforehand for I'm a newbie in Rust.
Regarding #1294,  I've introduced a new struct wrapper around `SentinelClient` to make it possible to use it with the macro used in `r2d2.rs`.
The usage will be something like this: 
```rust
pub struct PooledSentinelClient;
impl PooledSentinelClient {
pub fn new_pool(
cfg: &crate::config::RedisSentinelConfig,
server_type: &str,
) -> anyhow::Result<Pool<sentinel::LockedSentinelClient>> {
let server_type = match server_type {
"master" => SentinelServerType::Master,
"slave" => SentinelServerType::Replica,
_ => bail!("invalid server type provided: {}", cfg.sentinel.master_name),
};
let sentinel_client = SentinelClient::build(
vec![format!("redis://{}", cfg.address)],
cfg.sentinel.master_name.clone(),
None,
server_type,
)?;
let pool = …
```
> Add r2d2 support for SentinelClient

- Makefile
- redis/src/aio/async_std.rs
- redis/src/aio/mod.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/aio/pubsub.rs
- redis/src/aio/runtime.rs
- redis/src/aio/tokio.rs
- redis/src/client.rs
- redis/src/cluster_async/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_cluster_async.rs
This change will ensure that a multiplexed connection will
abort the spawned task driving the connection once all
of the connection's clones have been dropped.
This change only affects users who have created a
multiplexed connection without manually spawning its
backing task. Those who do should manage the task by themselves.
https://github.com/redis-rs/redis-rs/issues/1236
> Abort backing task to multiplexed connection on drop.

- redis/Cargo.toml
- redis/src/r2d2.rs
The new 'sentinel' feature in redis-0.27.0 will cause a compile error when the configuration includes `features = ["tokio-comp","r2d2", "connection-manager"]` without sentinel
error log:
```
error[E0432]: unresolved import `crate::sentinel`
--> /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redis-0.27.0/src/r2d2.rs:1:12
|
1   | use crate::sentinel::LockedSentinelClient;
|            ^^^^^^^^ could not find `sentinel` in the crate root
|
note: found an item that was configured out
--> /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redis-0.27.0/src/lib.rs:607:9
|
607 | pub mod sentinel;
|         ^^^^^^^^
note: the item is gated behind the `sentinel` feature
--> /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redis-0.27.0/src/lib.rs:605:7
|
605 | …
```
> fix sentinel feature error and update dependency

- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
Redis supports adding a `[TYPE type]` subcommand to SCAN since 6.0.0
Similar to a `[MATCH pattern]`, this will filter the returned values, but does not actually reduce the amount of work done by Redis. The TYPE subcommand is only supported on SCAN. SSCAN, HSCAN and ZSCAN does not support it. 
This PR adds basic support for the `[TYPE type]` subcommand. It simply adds a `with_type` method to the existing `ScanOptions`. Currently it takes an arbitrary string, which should be a Redis type, e.g. "string" or "hash". 
This PR should be fully backwards compatible.
> Add support for [TYPE type] in SCAN commands

- redis/src/cluster.rs
The sync cluster client now uses the same default timeouts as the async client. Additionally, now `ClusterClient::response_timeout` and `ClusterClient::connection_timeout` will actually do something on the sync cluster client.
> Align default timeouts on cluster client.

- Cargo.lock
- redis/Cargo.toml
- redis/src/aio/connection_manager.rs
[`tokio-retry`](https://crates.io/crates/tokio-retry) has been unmaintained for over 3 years now, so this new crate, [tokio-retry2](https://crates.io/crates/tokio-retry2), is being used by my project. 
It has new features like the ability to early exit with wrapping errors (RetryError::Permanent), or continue the retry loop (`RetryError::Transient`), as well a notification on fail system (which was not included in this PR, but can be easily done replacing `Retry::spawn(..)` with `Retry::spawn_notify(..)` .
> Updates unmaintained tokio-retry to tokio-retry2

- .github/workflows/rust.yml
This refactors the CI pipeline to not use a cartesian product of Rust & DB version, and instead of test all Rust versions against a single DB version, and all DB versions against stable Rust, since the two are orthogonal.
This allows us to add more DB types and versions and only add 1 CI action per version.
> Test against Valkey in CI.

- redis/src/cluster.rs
- redis/src/cluster_client.rs
- redis/src/connection.rs
Like username & password, Protocol & TLS will now be copied from the first node if not explicitly set, and then verified that the same value is set for all other initial nodes.
https://github.com/redis-rs/redis-rs/issues/1288
> Align verification of protocol & TLS during cluster creation.

- redis/src/lib.rs
Discord user magefulrage suggested having the `use futures_util::StreamExt;` line in the PubSub example in the documentation would be helpful.
> Include the StreamExt use statement in docs

- redis/src/commands/mod.rs
- redis/src/streams.rs
- redis/tests/test_streams.rs
Adds the lastid option to xclaim
https://redis.io/docs/latest/commands/xclaim/
This is one of the items in #1153
Behavior of LASTID is documented here:
https://github.com/redis/redis/blob/unstable/src/t_stream.c#L3123
(docs are missing on official redis docs https://redis.io/docs/latest/commands/xclaim/ )
> Add lastid option to xclaim

- redis/src/commands/mod.rs
- redis/src/streams.rs
- redis/tests/test_streams.rs
- these support the full command set for the commands
- nomkstream on xadd
- minid/limit for trimming
This implements more functionality for #1153
> Add xadd_options and xtrim_options

- redis/src/connection.rs
- redis/tests/support/mod.rs
- redis/tests/test_basic.rs
the sync client will keep a counter for requests that were answered before the response was received by the server, and will skip those responses before answering the user.
fixes https://github.com/redis-rs/redis-rs/issues/1252
> Sync connection: Handle timed-out responses by ignoring them.

- .github/workflows/rust.yml
We have more tests = we have more timeouts :shrug:
> Increase test CI action timeout.

- redis/Cargo.toml
- redis/src/aio/connection_manager.rs
- redis/tests/test_async.rs
The connection and response timeouts in `MultiplexedConnection` are truly optional: they are wrapped in `Option`, and if they are `None`, the runtime's `timeout` function is never called at all.
`ConnectionManager` currently mimics an optional timeout by using `Duration::MAX` as the default timeout value.  The runtime's `timeout` function is called, but with an incredibly large duration.
In normal operation, this would not be a problem, since the timeouts will not fire unless the process runs for ~half a trillion years.  But it breaks test cases that use Tokio's [pausable clock][].  If the task invoking Redis is parked (e.g. while waiting for the Redis command to complete), Tokio will [auto-advance the clock][] to the next sleep point, allowing the timeout to fire.
This patch updates the …
> Allow disabling timeouts in `ConnectionManager`

- redis/src/aio/multiplexed_connection.rs
- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_client.rs
- redis/src/cluster_routing.rs
- redis/src/cmd.rs
- redis/src/commands/macros.rs
- redis/src/connection.rs
- redis/src/geo.rs
- redis/src/sentinel.rs
- redis/src/types.rs
Most of the changes here involve taking a large block of test and splitting off the first line. docs.rs shows only the first paragraph of a doc in an upper scope as blurb, and these types had outlandishly long blurbs.
> Improve docs.

- Cargo.lock
- redis/Cargo.toml
- redis/src/aio/connection_manager.rs
- redis/src/aio/runtime.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
tokio_retry apparently doesn't work with async-std, and we didn't notice that because the tests enabled immediate reconnection. This happened because the reconnection was tested with a working server, so the connection manager could reconnect immediately.
> Use runtime agnostic retry mechanism.

- redis/src/aio/runtime.rs
- redis/src/cluster_async/mod.rs
The current implementation caused the occasional error in async-std tests, where both tokio & async-std-comp features are turned on, and the default sleep is with tokio.
```
test cluster_async::test_async_cluster_basic_failover::case_2_async_std ... Panic: panicked at redis/src/cluster_async/mod.rs:231:21:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
Panic: panicked at redis/tests/test_cluster_async.rs:509:33:
redis_cluster: Unable to receive command
```
> Choose sleep function according to active runtime.

- README.md
- redis/src/lib.rs
To avoid trademark issues, describe this as a library "for Redis" rather than a "Redis library".
> Describe as "for Redis"

- .config/nextest.toml
- .github/workflows/rust.yml
- Makefile
nextest provides better outputs on tests, and will allow us to find slow & flakey tests.
> Use cargo-nextest for testing.

- redis/src/aio/connection_manager.rs
- redis/src/aio/mod.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/client.rs
- redis/src/types.rs
This allows the users to use more channels, and to define new channels to use.
See request in https://github.com/redis-rs/redis-rs/issues/1291
> Async push messages: Allow for more channel types.

- README.md
To use rustls, we have to add `rustls` to the dependencies, then install the crypto provider in the main fn
```toml
[dependencies]
rustls = { version = "0.23", features = ["ring"] }
```
```rust
fn main() {
rustls::crypto::ring::default_provider()
.install_default()
.expect("Failed to install rustls crypto provider");
// ...rest of your code
}
```
> Update README to use rustls

- .config/nextest.toml
Slow tests are now defined as any test taking longer than 1 second.
> Report slow tests more eagerly.

- README.md
Running make test is advised in README.md , it's better to document what it requires to run it.
Related to: https://github.com/redis-rs/redis-rs/pull/1336
> Update README.md regarding cargo-nextest

- redis/examples/async-connection-loss.rs
- redis/examples/async-multiplexed.rs
- redis/src/client.rs
- redis/tests/support/mod.rs
Replaced with the more general `get_multiplexed_async_connection`.
> Replace `get_multiplexed_tokio_connection` in examples & tests.

- redis/src/aio/connection_manager.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/connection.rs
- redis/src/r2d2.rs
- redis/src/types.rs
- redis/tests/test_async.rs
This change allows the ConnectionManager to reconnect not only when receiving errors on requests, but also when receiving disconnect pushes on the push channel from the internal connection.
Based over https://github.com/redis-rs/redis-rs/pull/1392
> ConnectionManager: reconnect on disconnect pushes.

- redis/src/aio/connection_manager.rs
- redis/src/lib.rs
- redis/src/subscription_tracker.rs
- redis/tests/test_async.rs
This change adds a configuration to allow the ConnectionManager to automatically resubscribe on pubsub channels after reconnection.
This is left as an opt-in configuration in order not to break backwards-compatibility.
Based over https://github.com/redis-rs/redis-rs/pull/1407 & https://github.com/redis-rs/redis-rs/pull/1392
> ConnectionManager: Support automatic resubscription.

- redis/src/aio/pubsub.rs
- redis/src/commands/mod.rs
- redis/src/connection.rs
- redis/tests/test_async.rs
- redis/tests/test_basic.rs
RESP2 allows pubsub connections to send PINGs on the connection without breaking from the pub/sub contract. This change adds `ping` and `ping_message` methods to all pubsub implementations, so that they could send the pings.
For the sync pubsub connection this requires saving responses from the server which aren't pubsub messages, instead of just returning completion from user requests.
https://github.com/redis-rs/redis-rs/issues/639
> Add ping support to commands & pubsubs.

- redis/src/aio/connection.rs
- redis/tests/test_async.rs
This is in preparation of actually deleting the type from the library.
> Mark more `Connection` functions as deprecated.

- redis/src/aio/multiplexed_connection.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_async/request.rs
- redis/src/cluster_client.rs
- redis/src/commands/mod.rs
- redis/src/lib.rs
- redis/src/types.rs
- redis/tests/support/mock_cluster.rs
- redis/tests/support/mod.rs
- redis/tests/test_cluster_async.rs
This change allows users to set a push sender on a cluster connection, subcscribe & unsubscribe from channels, channel patterns, and sharded channels, and receive pubsub messages.
The cluster connection will automatically resubscribe when a connection will disconnect, or after a topology change.
> Async Cluster: Add pubsub support.

- Cargo.lock
- redis/Cargo.toml
- redis/src/types.rs
The same logic can easily be expressed with only Iterator methods.
> Remove itertools dependency

- redis/Cargo.toml
- cluster-async requires aio
- futures-util is always used with the same features, declare them in the [dependencies] table rather than the only feature that activates the dependency
> Clean up feature dependencies

- .config/nextest.toml
Locally it runs in about ~13 seconds, in CI it occasionally reaches even higher. Also increase the slow marking level to 2 seconds, since a lot of tests run in the range of 1-2 seconds.
https://github.com/redis-rs/redis-rs/issues/1477
> Double test_async_cluster_basic_failover timeout.

- redis/src/lib.rs
Noticed that while the `retry_method()` function was exported the type wasn't, this was due to it being missing from `lib.rs` it seems.
Could this be included in a minor release in version 28?
> Fix RetryMethod Import

- redis/src/cmd.rs
- redis/src/types.rs
As discussed in #890.
The goal of this is to allow compatibility with `std::io::Write`-based serializers in `ToRedisArgs` implementations, and more generally to allow serializers that write to a buffer in chunks to be able to write directly to `redis::Cmd`'s internal buffer, instead of having to write it to an external buffer, then copy that into `redis::Cmd`'s internal buffer.
This does not affect `redis::Cmd`'s own serialization behavior, which will still copy that internal buffer once. However, one copy is better than two for this use case.
I also have a guard implementation for `std::io::Write` here https://gist.github.com/swwu/f3e21a5c939e06c20f445735ee75d358 that I'd be happy to throw in, but it's a bit more opinionated and I'm not completely clear on where it would go.
I'm not …
> Add buffered write methods to RedisWrite

- redis/src/aio/connection.rs
- redis/src/aio/connection_manager.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/aio/pubsub.rs
- redis/src/cluster_async/mod.rs
- redis/src/connection.rs
- redis/src/lib.rs
The docs should now be clearer that the user can subscribe or unsubscribe from multiple channels in a single call.
https://github.com/redis-rs/redis-rs/issues/1518
> Improve pubsub docs.

- redis/src/client.rs
- redis/src/cluster_client.rs
- redis/src/lib.rs
- redis/src/sentinel.rs
- redis/src/tls.rs
- redis/tests/support/sentinel.rs
- redis/tests/test_sentinel.rs
We would like to be able to configure the TLS certificates that are used with Sentinel. Similar functionality was already included in https://github.com/redis-rs/redis-rs/pull/858, but it was reverted and was said to better be included in a separate PR.
There are two connections for which we would like to configure the certificates:
1. Client <-> Redis. This is done in 2954990dcee076d9d3fbca1b771e12d05379be24 by adding a field `certs` to `SentinelNodeConnectionInfo`. This is a breaking change but I think it's quite hard to include this functionality without any breaking changes. For example, `Sentinel` offers several `pub fn`, such as `master_for`, which would need some access to the certificates. If we don't want to change the signature of these function we would need to duplicate them. …
> Allow configuring Sentinel with custom TLS certificates

- redis/tests/test_cache.rs
This will mean that they will be filtered in `make test`, which makes it easier to run local tests without having Redis JSON installed.
> Renaming tests the require the JSON module

- redis/Cargo.toml
- redis/src/aio/async_std.rs
- redis/src/aio/connection.rs
- redis/src/aio/connection_manager.rs
- redis/src/aio/mod.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/aio/tokio.rs
- redis/src/client.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_client.rs
- redis/src/connection.rs
- redis/src/io/mod.rs
- redis/src/io/tcp.rs
- redis/src/lib.rs
https://github.com/redis-rs/redis-rs/issues/1470
https://github.com/redis-rs/redis-rs/issues/1147
ATM this change is only for async connections, in order to get early feedback quickly. This can technically be added to sync connections too.
> Allow users of async connections to set TCP settings.

- redis-test/src/cluster.rs
- redis/src/io/tcp.rs
- redis/tests/support/cluster.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
In trying to add a test for a new security mode in https://github.com/redis-rs/redis-rs/pull/1529, I found out no existing cluster tests run in `TlsMode::Secure` mode. It seems like a good idea to get some coverage for that case first.
All but 6 tests pass with certificate checking enabled, so this PR transitions tests to run in `Secure` mode by default when `rustls` is used, and explicitly opts out those 6 tests.
This is `tls-rustls` only for now. TLS support in the cluster tests works by generating a one-off root cert (to sign the server cert), and it appears `redis-rs` doesn't support adding a root cert to the client in `tls-native-tls` builds, so certificate checking would always fail.
> Run most cluster tests in secure mode when rustls is enabled

- redis/src/lib.rs
I just added `disable-client-setinfo` optional feature in the documentation.
See #1535
> docs: added CLIENT SETINFO optional feature

- redis/src/aio/mod.rs
- redis/src/connection.rs
- redis/src/pipeline.rs
- redis/tests/test_basic.rs
Closes #1538 
Exposes the `Pipeline.len()` function as discussed in #1538. Adds a simple test to ensure that the interface is constant.
> Expose `Pipeline.len()` function as public

- redis-test/src/cluster.rs
- redis-test/src/utils.rs
- redis/src/aio/async_std.rs
- redis/src/aio/mod.rs
- redis/src/aio/tokio.rs
- redis/src/cluster.rs
- redis/src/cluster_client.rs
- redis/src/connection.rs
- redis/src/tls.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
Fixes #1500.
This adds a new insecure connection mode between `TlsMode::Secure` and `TlsMode::Insecure`, called `danger_accept_invalid_hostnames` after the flag in `tls-native` that implements it. When this mode is enabled, certificate checking still happens, but the hostname in the certificate is not required to match the server we're trying to connect to.
**The new mode is not a new `TlsMode`** or a new field on `TlsMode::Insecure`. Either of those would be a better API, I think, but it'd be a breaking change. So this PR adds the new option as a `ClusterClientBuilder` method instead. When you use this, the `tls_mode` says `Secure` even though you've configured a hole in the TLS security. :-\
I don't actually need the rustls version, but I implemented the option for both `tls-rustls` and …
> Implement `danger_accept_invalid_hostnames` option.

- redis/src/connection.rs
Allows a URL like `valkey://127.0.0.1:6379`.
Addresses issue: https://github.com/redis-rs/redis-rs/issues/1555
Valkey supporting the scheme: https://github.com/valkey-io/valkey/pull/199
> Add Valkey URL scheme

- redis/src/types.rs
- redis/tests/test_types.rs
The unreachable code assumed that a nested array has to be able to converted to the target tuple, and so panicked when when the array is larger. Instead, we should just fallback to the next piece of code, and allow the array to be split into multiple returns of the target tuple.
https://github.com/redis-rs/redis-rs/issues/1561
> Fix unreachable error when parsing a nested tuple. 

- Cargo.lock
- redis/Cargo.toml
- redis/src/bb8.rs
- redis/src/lib.rs
Part of https://github.com/redis-rs/redis-rs/issues/1563
---
My original plan was to use the bb8 code directly, but I decided to follow the same pattern as r2d2 instead.
> feat: Add bb8 support for async client

- redis/src/cluster_async/mod.rs
- redis/src/cluster_async/routing.rs
I don't think there is any reason not to do this concurrently? Each connection will be to a different node and they will mostly just wait for IO which is nice to do concurrently.
Also refactored a bit to remove `ConnectionFuture` as it does not seem to serve a purpose anymore.
(Looking over the implementation to try and debug a connection problem and spotted it).
> perf: Run reconnection attempts concurrently

- redis/src/cluster_async/routing.rs
- redis/src/commands/mod.rs
- redis/src/lib.rs
- redis/tests/support/mod.rs
- redis/tests/test_cluster_async.rs
We tend to run flushing commands in our tests, and it would be great to be able to do that directly on the connection, like
```
conn.flushdb().await?;
```
> Add commands to flush database(s)

- redis/src/connection.rs
This adds some changes, that (I assume) were forgotten in https://github.com/redis-rs/redis-rs/pull/1558.
- "valkey" and "valkeys" were not able to be converted to a connection info https://github.com/redis-rs/redis-rs/blob/8db06bf4e67c526a0604c8d3bc15ae7acf281a0e/redis/src/connection.rs#L463-L464
- "valkeys" did not get treated the same as "rediss" https://github.com/redis-rs/redis-rs/blob/8db06bf4e67c526a0604c8d3bc15ae7acf281a0e/redis/src/connection.rs#L363-L393
- "valkey+unix" protocol scheme was missing (equivalent to "redis+unix")
> Fix valkey(s) url schemes not able to be converted to connection infos; Add valkey+unix url scheme

- redis/src/bb8.rs
Hi, this PR add support bb8 for `redis::cluster::ClusterClient` inspired by the #1564.
Thank you for these work, any feedback is appreciated.
> Support bb8 for cluster client

- redis/src/aio/connection_manager.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/client.rs
- redis/src/cluster_async/mod.rs
This PR tries to fix the warnings of running `make docs`
The only missing issue is `redis/src/aio/connection.rs:99`
There, the `PubSub` link in the documentation
```
/// Converts this [`Connection`] into [`PubSub`].
#[deprecated(note = "aio::Connection is deprecated. Use [Client::get_async_pubsub] instead")]
pub fn into_pubsub(self) -> PubSub<C> {
PubSub::new(self)
}
```
does not work. The warning I get is:
```
warning: public documentation for `into_pubsub` links to private item `PubSub`
--> redis/src/aio/connection.rs:99:45
|
99 |     /// Converts this [`Connection`] into [`PubSub`].
|                                             ^^^^^^ this item is private
|
= note: this link will resolve properly if you pass `--document-private-items`
= note: `#[warn(rustdoc::private_intra_doc_links)]` …
```
> Fix `make docs`

- Cargo.lock
- Makefile
- config/redis.toml
- redis/Cargo.toml
- redis/src/aio/connection.rs
- redis/src/aio/mod.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/aio/pubsub.rs
- redis/src/aio/runtime.rs
- redis/src/aio/smol.rs
- redis/src/aio/tokio.rs
- redis/src/client.rs
- redis/src/lib.rs
- redis/src/sentinel.rs
- redis/tests/parser.rs
- redis/tests/support/mod.rs
- redis/tests/test_async.rs
- redis/tests/test_cache.rs
- redis/tests/test_cluster_async.rs
- redis/tests/test_sentinel.rs
Since async-std is [officially deprecated](https://www.reddit.com/r/rust/comments/1jc6gis/psa_asyncstd_has_been_officially_discontinued_use/), this change adds explicit support for the Smol runtime. In the future the async-std features will be removed - in the meanwhile, since AFAIS there's no way to trigger a compile warning by feature.
> Add support for the Smol runtime.

- redis/src/lib.rs
- redis/src/types.rs
This is done using the rustdoc internal feature `fake_variadic`, which requires a nightly compiler. Therefore this is gated behind the `docsrs` feature which is set by docs.rs.
This can be tested by running `RUSTDOCFLAGS="--cfg docsrs" cargo doc`.
Based on implementations in [Bevy](https://github.com/bevyengine/bevy/pull/14703) and [Serde](https://docs.rs/serde/latest/src/serde/ser/impls.rs.html#416).
I tried to avoid duplicating the trait implementations for the tuple with a single item, but the `fake_variadic` attribute needs to be on the implementation of the tuple with the single item, and can't be on the tuple with 12 items. Alternative would've been reworking how the macros work completely.
> Document variadic tuple implementations for FromRedisValue and ToRedisValue

- redis/src/cmd.rs
- redis/src/types.rs
I'm dealing with some legacy stuff where I need to serialize some data as ProtoBuf and send it via Redis. Currently this requires creating an extra buffer where I serialize the data, and then copy that data to the writer. This PR allows serializing directly into the writer.
This function is gated behind the "bytes" feature, which is automatically enabled with any of the async features.
A default implementation is provided, so that this is not a breaking change for upstream.
> Add an optional bytes::BufMut function to RedisWrite

- Cargo.lock
- config/redis.toml
- redis/Cargo.toml
Somewhat reduce the number of checks, and organize it to be more coherent with less redundant rules.
> Reorganize flag-frenzy comnfiguration

- redis/src/lib.rs
- redis/src/types.rs
- redis/tests/test_types.rs
`Error::source()` is the recommended method for accessing the error chain, and it should be used instead of `cause()` in modern Rust code.
Add unit tests that cover cases with and without an underlying source error.
> Implement Error::source for the RedisError struct

- redis/src/types.rs
`FromRedisValue` already supports `u128` and `i128` (although it's missing all the `NonZero` types).
> Add missing `u128`/`i128` for ToRedisArgs

- redis/src/aio/multiplexed_connection.rs
- redis/src/caching/cache_manager.rs
- redis/src/caching/cmd.rs
- redis/src/caching/mod.rs
- redis/src/client.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_client.rs
- redis/src/lib.rs
- redis/tests/test_cache.rs
This is quite a small change because most of the logic is already implemented in other modules used by ClusterConnection.
I wanted to consolidate cache tests nicely across mpx,cm and cluster connections but so far failed to do so.
With that reason patch adds two new tests.
Also I have tested slot change on Redis 8, when there is a slot change redis will send invalidation but couldn't write a simple test for it.
> Add Client Side Caching for async Cluster Connections

- README.md
- redis/Cargo.toml
- redis/examples/async-typed.rs
- redis/examples/typed.rs
- redis/src/commands/macros.rs
- redis/src/commands/mod.rs
- redis/src/lib.rs
- redis/src/types.rs
- redis/tests/test_basic.rs
A solution to #1228 and #1322 , as described by @nihohit.
Introduce two new traits `TypedCommands` and `AsyncTypedCommands` that behave like their non-typed counterparts, but return specifically opinionated types instead.
The return types are defined in the existing place in `commands/mod.rs` that defines the inputs for `Commands` and `AsyncCommands`. The existing macros for generating `Commands` and `AsyncCommands` will ignore the return type, while the new ones for the typed variants will include those types in the generated methods. Additionally, if a return type is omitted, it will default to `redis::Value`.
> Add new set of typed commands

- redis/src/aio/connection_manager.rs
- redis/src/caching/sharded_lru.rs
- redis/src/cluster_async/mod.rs
We've been investigating some tokio poll latency spikes that then lead to timeouts in some redis accesses. One of the theories going around is that it might be bug in this library. I have audited `Mutex` and `RwLock` uses and found some lock guards that are being kept alive a little longer than necessary, so here's a PR to fix that (though it seems very unlikely that any of these changes are related to our issue - the bug hunt continues).
> Minimize the lifetime of mutex lock guards

- Makefile
- redis/examples/async-scan.rs
- redis/src/cmd.rs
- redis/tests/test_async.rs
When the `safe_iterators` feature isn't implemented, the `Stream` implementation of AsyncIter should return T, not `RedisResult<T>`.
> Fix AsyncIter implementation of stream.

- redis/src/pipeline.rs
When trying to mock Redis connections, the `ConnectionLike`'s `req_packed_commands` expects a different response shape on `transactional` and non-`transactional` pipelines.
(Vec with single entry of Redis array of results, resp. Vec of results)
In order to hide this difference from users, it would be helpful to check if a pipeline is in transaction mode or not.
To allow this, we make the accessor function public.
> feat: Make transaction status of pipelines public

- .github/workflows/rust.yml
- Cargo.lock
- Makefile
- README.md
- config/global.toml
- config/redis.toml
- redis-test/Cargo.toml
- redis/Cargo.toml
- redis/examples/async-scan.rs
- redis/examples/basic.rs
- redis/src/cmd.rs
- redis/src/lib.rs
- redis/tests/test_async.rs
- redis/tests/test_basic.rs
This change removes the usage of unsafe iterators.
> Remove unsafe iterators.

- redis/src/sentinel.rs
- redis/tests/test_sentinel.rs
The current `redis::sentinel::SentinelClient` api is limited to `get_connection` and `async_get_connection`. In order to establish connections to the correct (master/replica) Redis instance, it will first attempt to find the master/replica and create a `redis::Client` pointing at it. 
This PR makes `get_client` and `async_get_client` publicly available so users have the ability of getting such `redis::Client` and use it directly without going through sentinel facade.
Additionally, I'm adding a method that allows a user to obtain a `redis::Client` that points to one of the provided Sentinel instances. Having such a client allows, for instance, to leverage `pubsub` to subscribe to Sentinel events.
> feat: extend sentinel api to be a bit more flexible

- redis/src/types.rs
- redis/tests/test_types.rs
The blocks that tried to convert internal collections to tuples caused bad results if some of the values in the items array could be converted to tuples and others couldn't.
```rs
for item in items {
match item {
Value::Array(ch) => {
if  let [$($name),*] = &ch[..] {
rv.push(($(from_redis_value(&$name)?),*),)
};
},
_ => {},
}
}
if !rv.is_empty(){
return Ok(rv);
}
```
So it was replaced with a block that first verifies that all of the values in the collection can be converted to the tuple.
```rs
if items.iter().all(|item|item.is_collection_of_len(n)) {
return items.iter().map(|item|from_redis_value(item)).collect();
}
```
Fixes https://github.com/redis-rs/redis-rs/issues/1674
> Fix handling of nested tuples.

- redis/src/cluster.rs
When attempting to connect to a clustered Redis instance, if there is some kind of network misconfiguration, the only error message you get back is `It failed to check startup nodes.` which doesn't help to diagnose the connection problem.
This PR formats and combines the individual reasons for failing to connect to each initial node in the cluster, and concatenates them into the "details" of the error message.
> Propagate connection error when failing to connect to clustered redis

- .github/workflows/rust.yml
- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
This Pull Request introduces support for additional logical bit operations using the `BITOP` command.
Extracts the members of `X` that are **not** in any of `Y1, Y2, …`.  
Logical form: `X ∧ ¬(Y1 ∨ Y2 ∨ …)`
Extracts the members in `Y1, Y2, …` that are **not** in `X`.  
Logical form: `¬X ∧ (Y1 ∨ Y2 ∨ …)`
Extracts members of `X` that are also in **any** of `Y1, Y2, …`.  
Logical form: `X ∧ (Y1 ∨ Y2 ∨ …)`
Extracts members that exist in **exactly one** of `X`, `Y1`, `Y2`, …  
Logical form:  `(X ∨ Y1 ∨ Y2 ∨ …) ∧ ¬((X ∧ Y1) ∨ (X ∧ Y2) ∨ (Y1 ∧ Y2) ∨ …)`
---
- ✅ Added a unit test covering both the original and newly added BITOP operators.
---
- Official Redis Documentation: [BITOP](https://redis.io/commands/BITOP)
- Initial [Pull Request](https://github.com/redis/redis/pull/13898) that introduces …
> Add new operators to the BITOP command

- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
fixes #1720
creates a method to call HMGET explcitly
I named the method `hget_multiple` to be consistent with `hset_multiple`
> add method hget_multiple to explicitly call HMGET

- .github/workflows/rust.yml
- redis/src/commands/mod.rs
- redis/src/streams.rs
- redis/tests/support/mod.rs
- redis/tests/test_basic.rs
- redis/tests/test_streams.rs
This Pull Request introduces new Redis Streams commands (`XDELEX` and `XACKDEL`) that provide enhanced control over message deletion and acknowledgment operations, specifically targeting **Redis 8.2+** features. The implementation adds support for fine-grained deletion policies that control how stream entries are handled with respect to consumer group Pending Entries Lists (PELs). It also extends the `XADD` and `XTRIM` commands with the same capabilities.
`XDELEX key [KEEPREF | DELREF | ACKED] IDS numids id [id ...]`
`XDELEX` accepts one of the following options: `KEEPREF` (default), `DELREF` or `ACKED`.
- Using the `KEEPREF` deletion policy deletes entries from the stream, but preserves existing references to those entries in all consumer groups' PELs. This behavior is similar to that of …
> Support Redis 8.2 stream command extensions and new deletion commands

- redis/src/script.rs
(The failing linter job seems unrelated. See #1748)
> docs: Fix usage of command/script of `ScriptInvocation::eval_cmd`

- redis/src/commands/mod.rs
- redis/src/script.rs
- redis/tests/test_script.rs
Having the `load_cmd` public allows to re-use it when loading scripts in pipelines.
> Make `Script`'s `load_cmd` public

- redis/src/aio/multiplexed_connection.rs
- redis/src/cmd.rs
- redis/tests/test_async.rs
- redis/tests/test_cluster_async.rs
Allows users to use `set_no_response` in order to skip waiting for the response. https://github.com/redis-rs/redis-rs/issues/1312
fixes https://github.com/redis-rs/redis-rs/issues/1312
> Allow async fire and forget.

- redis/src/cluster_handling/async_connection/mod.rs
- redis/src/subscription_tracker.rs
- redis/tests/test_cluster_async.rs
This changes the behavior of the cluster connection and the connection manager re: resubscribing on subscription that failed. The connection manager only registers successful subscription and unsubscription - which makes sense. It would be peculiar for the user if a connection that failed subscription would suddenly be subscribed after reconnection to the node.
> Align async resubscribe behavior.

- redis/src/commands/acl.rs
- redis/src/commands/geo.rs
- redis/src/commands/streams.rs
- redis/src/errors/mod.rs
- redis/src/errors/parsing_error.rs
- redis/src/parser.rs
- redis/src/types.rs
This should allow users to build these errors on their implementations of `FromRedisValue`.
> Enable more ways to build a parsing error.

- redis/src/commands/mod.rs
command`hexpire_at` takes UNIX timestamp in seconds. See https://redis.io/docs/latest/commands/HEXPIREAT/
> docs: fix `hexpire_at` command measurement unit

- redis/CHANGELOG.md
- redis/src/cluster_handling/async_connection/mod.rs
- redis/src/errors/redis_error.rs
- redis/tests/test_cluster_async.rs
Calls that previously failed due to RedisError will now try to propagate those better.
> Handle server errors more robustly in async aggregate responses.
