- .travis.yml
- README.md
- src/connection.rs
the travis.yml has been fixed to execute the builds.
connection.rs has been modified to access Non-default databases.
> Fix the travis build and allow connection to non default databases

- src/connection.rs
Hi Armin,
I've created Redis connection pooling using Steven Fackler's https://github.com/sfackler/r2d2. I needed Clone and Debug on the ConnectionInfo.
So I hope you take a look at https://github.com/nevdelap/r2d2-redis, tell me what you think.
Cheers.
> Add derive Clone and Debug to ConnectionInfo

- src/parser.rs
Might be faster than allocating a buffer for each byte.
> parser.read(): try to read all bytes at once

- README.md
Super small, subject says it all.
> Update README.md to specify latest crate

- Cargo.toml
- src/connection.rs
- tests/test_basic.rs
See https://github.com/servo/rust-url/commit/9e759f18726c8e1343162922b87163d4dd08fe3c
Cheers
> Update rust-url to 1.1 and add test for parse_redis_url

- src/types.rs
> Implement ToRedisArgs for &String to make it work without slicing

- CHANGELOG.md
Changelogs are great to see what changed in a library. I went through the commits and the related pull requests, hopefully everything I wrote is correct.
> Update changelog for 0.5.4 and 0.6.0

- src/connection.rs
I am pretty certain this was just a find and replace error, thank you for the amazing library!
> Fix compilation when unix socket features are disabled

- Cargo.toml
> Update URL version

- .travis.yml
- Makefile
ref https://github.com/mitsuhiko/redis-rs/issues/99
> Use Makefile for tests

- src/commands.rs
- tests/test_basic.rs
> Fix setbit

- src/lib.rs
> Don't hide docs of types

- src/types.rs
- tests/test_basic.rs
- tests/test_types.rs
Added as a PR for reference.
Successor of #116
> Rebase of #116: BTreeMap/Set conversions

- src/commands.rs
- tests/test_basic.rs
Tiny addition to implement lset
> Implements LSET command.

- .travis.yml
- Makefile
Should speedup the travis builds a bit.
> chore: Cache cargo on travis

- Cargo.toml
- src/cmd.rs
- src/lib.rs
- src/parser.rs
- src/types.rs
> fix: Make RedisFuture Send

- src/commands.rs
> feat: add ttl command

- benches/bench_basic.rs
- build.rs
- examples/basic.rs
- src/async.rs
- src/cmd.rs
- src/connection.rs
- src/lib.rs
- src/parser.rs
- src/script.rs
- src/types.rs
- tests/parser.rs
- tests/support/mod.rs
- tests/test_async.rs
- tests/test_basic.rs
- tests/test_types.rs
The formatting should be (more or less) stable now so it would be nice
to have the project updated to it.
> style: Run cargo fmt

- src/async.rs
- src/client.rs
- tests/support/mod.rs
The crate now requires rust 1.26
> perf(async): Use impl Future instead of boxing where possible

- src/connection.rs
I'm taking over #153.
This solves issue #152 and obsoletes #153.
BTW: I don't know if there is someone so crazy that they use an invalid UTF-8 string as passwords. Maybe we can wait until they appear.
> Fix handling of passwords with special characters

- CHANGELOG.md
As requested by @badboy in https://github.com/mitsuhiko/redis-rs/pull/206#issuecomment-493459811
> docs: mention async Script in changelog

- src/aio.rs
- tests/test_async.rs
The task that drives `SharedConnection` is supposed to shutdown
automatically once the last reference to it is dropped. It did not do
that due to the `poll_read` call in `close` which registered another
`read` on the socket. Since this socket only produces data in response
to any requests done to redis and the last `SharedConnection` reference
were dropped there will only be more data to read while there are
requests in flight.
This ensures that we only drive the socket until those requests are done
whereafter we shut it down.
Tests did not catch this because they only waited for the main task to
finish which were fixed with `block_on_all`.
> fix(async): Don't block the executor from shutting down

- .travis.yml
- Makefile
- src/aio.rs
- src/cmd.rs
- src/commands.rs
- src/connection.rs
- src/geo.rs
- src/parser.rs
- src/script.rs
- src/types.rs
- tests/support/mod.rs
- tests/test_async.rs
- tests/test_basic.rs
- tests/test_geospatial.rs
- tests/test_types.rs
I wanted to do this for a long time.  This is one of my oldest crates and I never
got to clean this up.
> Run clippy over the entire codebase

- src/client.rs
- src/connection.rs
Add get_connection_with_timeout to Client which acts like get_connection but gets a timeout for connecting
> Add get_connection_with_timeout to Client

- src/commands.rs
> Added support for PSETEX and PTTL commands.

- examples/async-await.rs
If this is accurate and of interest, I would like to add an additional function that demonstrates parallelism using `MultiplexedConnection`.
> Add async/await example.

- src/client.rs
- src/commands.rs
- src/lib.rs
Like in https://docs.rs/tokio/0.2.6/tokio/index.html#modules
> doc: Call out feature gated functions/modules/etc in docs

- Cargo.toml
- Makefile
- src/client.rs
- src/cmd.rs
- src/commands.rs
- src/lib.rs
- src/script.rs
- tests/support/mod.rs
Introduces a new `aio` default feature that allows to turn off some tokio dependencies.
> Reduce dependencies without AIO

- CHANGELOG.md
Just a bit of malformed markdown :slightly_smiling_face:
> Fix issue link in CHANGELOG

- src/aio.rs
Regressed in #232 (there is a comment explaining what should be done,
only it wasn't anymore)
Fixes #275
> fix: Don't hang in the multiplexed connection if the server shuts down unexpectedly

- Cargo.toml
- src/aio.rs
- src/commands.rs
- src/parser.rs
> fix: Make aio::Connection Sync again

- src/cmd.rs
- src/types.rs
Two small improvements and added a pair of helper functions for working with sequences and maps inside `Value` which could be useful to avoid intermediate structures like https://github.com/mitsuhiko/redis-rs/pull/319/files#diff-6162c7f34c4c3cad920338d2f8d00903R483 (cc @Terkwood )
> Remove some unnecessary overhead around Value conversions

- src/commands.rs
- src/types.rs
- tests/test_types.rs
Greetings!
I _think_ this fixes the macro so that it's correct.  Found as a result of working through #319.
See this portion of the PR, specifically: https://github.com/mitsuhiko/redis-rs/pull/319#discussion_r435184148
> Count items correctly in tuple macro

- README.md
Adding cluster info as discussed in #339 
Just curious, is adding one node enough (will it automatically discover the others)?
If so we can add that to `readme` as well.
> Update README.md for cluster support

- src/script.rs
> Add Debug and Clone implementations to redis::Script

- src/lib.rs
"you" seems like a typo, replace with comma to clarify language.
> Clarify language in iteration protocol doc string

- Cargo.toml
- README.md
- appveyor.yml
- src/aio.rs
- src/aio/async_std.rs
- src/aio/tokio.rs
- src/client.rs
- src/lib.rs
- src/parser.rs
- tests/parser.rs
- tests/support/mod.rs
- tests/test_async.rs
Closes #396
Tokio 0.2 support is dropped to support tokio 0.3
> feat: Update tokio dependency to 0.3

- src/commands.rs
add support for DECRBY, the opposite of the currently implemented INCRBY
> add support for decr

- src/commands.rs
- src/lib.rs
> add support for LPOS command

- Cargo.toml
- src/aio.rs
- src/parser.rs
> feat: Update to tokio 1.0

- src/commands.rs
- tests/test_basic.rs
Greetings,
This is a small PR for supporting non-blocking delete via the UNLINK command.
https://redis.io/commands/unlink
> Add support for UNLINK command

- src/cluster.rs
The XREAD/XREADGROUP commands can have a variable number of args,
and proper routing of the command relies on finding the key after
the "STREAMS" keyword. This was failing to properly route the if
the keyword was not uppercase. Fixes the matching logic make each
arg uppercase before comparing to the "STREAMS" keyword.
> Fix incorrect routing for XREAD/XREADGROUP command

- src/commands.rs
- tests/test_basic.rs
> Fix zrembylex command

- src/cluster.rs
- tests/test_cluster.rs
Implements efficient routing for pipeline commands with Redis Cluster. For every command in the pipeline, determines which node is responsible for it and builds a pipeline per node. Each pipeline is first sent to its respective node, then all responses are read back. Any commands that can be retried are done individually.
This leads to a huge performance gains with a pipeline of 100 commands.
Before:
```
time:   [8.3241 ms 8.3772 ms 8.4356 ms]
thrpt:  [11.854 Kelem/s 11.937 Kelem/s 12.013 Kelem/s]
```
Now:
```
time:   [383.37 us 389.66 us 396.19 us]
thrpt:  [252.41 Kelem/s 256.63 Kelem/s 260.84 Kelem/s]
```
> Efficient ClusterPipeline routing

- examples/streams.rs
- src/commands.rs
- src/streams.rs
- src/types.rs
- tests/test_streams.rs
Closes #496 
Previous discussion here: https://github.com/TilBlechschmidt/redis-rs/commit/ddf6902c08b03a6bc858afea3585ecce12c0edb3#r51877701
I think it makes sense to continue discussions in the context of a PR.
> Make xread_options take &StreamReadOptions

- src/aio.rs
Generates less code and better stacktraces
> refactor: Prefer mapping over Result over Futures

- src/aio.rs
It is already ambiguous whether the command will run or not if the
receiver has dropped (it could have been dropped before the message was
sent over the channel). So if we see that there is no one to receive the
response before we have had a chance to send it over the wire then we
immediately drop the message instead.
This can help reduce load on the connection in circumstances where the
caller is overloaded and starts timing out on the requests.
> perf: Don't enqueue multiplexed commands if the receiver is dropped

- src/commands.rs
- src/macros.rs
- tests/test_basic.rs
> Add convenience command: zrandmember

- tests/test_async.rs
The failure can currently be seen on the last master branch build and on https://github.com/mitsuhiko/redis-rs/pull/562
I cant see any solution other than retrying or bumping the sleep up.
The unsub is triggered by the connection being dropped but only when redis notices the lost connection does the unsubscription occur. There is an inherent race condition that cannot be avoided here.
I opted to add a retry with timeout of 5s instead of just bumping the sleep to avoid increasing the runtime of the test on faster machines.
Happy to just bump the sleep up if a simpler solution is preferred.
> Fix intermittent ci failure

- Cargo.toml
- src/aio.rs
> Make dns resolution async, in async runtime

- README.md
> Add a Discord badge to README

- CHANGELOG.md
Close https://github.com/redis-rs/redis-rs/issues/688
> Fix changelog for 0.21.6

- redis/src/cluster.rs
- redis/src/cluster_client.rs
- redis/src/commands/mod.rs
- redis/src/types.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
Hello. I want to support @utkarshgupta137's PRs. (part 2, 3, 4, 5)
I think I can help with separating PRs. And I want to start with this PR (https://github.com/redis-rs/redis-rs/pull/690).
Firstly, I create 3 PRs. When there are something I should do more, feel free to notify to me!
- change some comments on cluster_client
- there no changes on code and not changes on binary
- this PR is dependent on https://github.com/redis-rs/redis-rs/pull/704
- you can check actual file changes on https://github.com/0xWOF/redis-rs/pull/13
> [2/5] [1] cluster_client: doc changes

- README.md
- redis/CHANGELOG.md
- redis/Cargo.toml
There are a few other incomplete PRs I would have liked to include in this release mentioned in #744, but I don't want to hold this any further given there are bug fixes waiting that have been ready to go out for awhile.
> 0.22.2 release

- redis/src/cluster_client.rs
Trivial grammar fix "the the".
> trivial typo/grammar fix

- redis/src/aio.rs
> Fix typo in `aio.rs`

- redis/src/cmd.rs
- redis/tests/test_async.rs
The `Stream` trait implementation was dropping the future on each `poll_next`, in some cases blocking forever if polling the Future returns `Poll::Pending`, ie. when more than 10 items are iterated
fixes: https://github.com/mitsuhiko/redis-rs/issues/583 and https://github.com/mitsuhiko/redis-rs/issues/537
It's my first time using Future's polling and streams, so reviews are more than welcome!
> Fix AsyncIter Stream trait implementation

- Makefile
- redis/Cargo.toml
- redis/src/cluster_async/LICENSE
- redis/src/cluster_async/mod.rs
- redis/src/lib.rs
- redis/tests/mock_cluster_async.rs
- redis/tests/support/cluster.rs
- redis/tests/support/mod.rs
- redis/tests/test_cluster_async.rs
Bring in code from https://github.com/redis-rs/redis-cluster-async
with minimal changes in order to allow for easier maintenance of
both projects and to better promote code reuse.
> Add Async Cluster Support

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
Make `SlotMap` a struct for better abstraction
and code de-duplication
> Newtype SlotMap

- redis/src/cluster_async/mod.rs
Started looking into the performance degradation in cluster_async. This isn't a big deal, but every little bit helps :)
> Reduce the number of unnecessary clones.

- .github/workflows/rust.yml
actions-rs is no longer maintained.
> Update and use better maintained github actions.

- redis/src/commands/mod.rs
- redis/src/streams.rs
- redis/tests/test_streams.rs
Fixes https://github.com/redis-rs/redis-rs/issues/959
Ordering also reported with Upstash Redis: https://github.com/upstash/issues/issues/74
> Fix XREADGROUP command ordering as per Redis Docs, and compatibility with Upstash Redis

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/src/connection.rs
- redis/tests/test_cluster_async.rs
That's the only scenario where it's needed.
rebased over https://github.com/redis-rs/redis-rs/pull/899
> Move response policy into multi-node routing.

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/tests/test_cluster.rs
This change aligns the sync cluster connection with the abilities of the
async cluster connection.
based over https://github.com/redis-rs/redis-rs/pull/952
> Sync Cluster: support multi-slot operations.

- README.md
- redis/src/connection.rs
I spent too much time trying to enable insecure mode for TLS at work, so I'm adding an example for the poor soul who needs to do the same.
> Updating Readme With Insecure TLS example

- redis/src/cmd.rs
- redis/src/connection.rs
- redis/src/macros.rs
- redis/src/types.rs
It has been made redundant by the ? operator.
> Remove the unwrap_or! macro.

- redis/src/cluster_routing.rs
This follows updates to the redis command tips:
https://github.com/redis/redis/pull/12530
https://github.com/redis/redis/pull/12545
> Align more commands routings.

- redis/src/types.rs
- redis/tests/test_types.rs
based on https://github.com/redis-rs/redis-rs/issues/468, https://github.com/redis-rs/redis-rs/pull/932.
> Add support for parsing to/from any sized arrays.

- redis/src/cmd.rs
- redis/src/script.rs
> [opt] preallocate buffer for evalsha in `Script`

- redis/src/commands/mod.rs
- redis/src/types.rs
> fix #1045: impl `Clone`/`Copy` for `SetOptions`

- Cargo.lock
https://github.com/advisories/GHSA-r8w9-5wcg-vfj7
> Update mio dependency due to vulnerability.

- redis/src/cluster_async/mod.rs
This removes unnecessary `match`es and `map` from the code, and moves the usage of `poll_recover` into `poll_flush`, so as not to block new requests while trying to recover a connection.
> Simplify Sink polling logic.

- redis/src/connection.rs
> impl `Clone` for `Msg`

- redis/tests/test_basic.rs
This PR adds PushManager tests into existings PubSub tests.
> Improve PushManager tests in sync connection

- redis/tests/test_cluster_async.rs
The loop slows the test down significantly - CI should find if this is flakey, not repeat runs of the test.
> Remove loop from test.

- redis/src/client.rs
- redis/src/cluster_client.rs
- redis/src/cluster_routing.rs
- redis/src/commands/json.rs
- redis/src/commands/mod.rs
- redis/src/streams.rs
- redis/src/types.rs
- redis/tests/test_types.rs
Backport of #1191 to 0.25 branch
> Fix explicit IoError not being recognized

- redis/src/cluster_async/mod.rs
- redis/tests/test_cluster_async.rs
This fixes a situtation where a multi-node request is sent after a disconnect, and is repeatedly being sent to the old, disconnected connection. This is caused by multi-node requests being routed with a specific connection, instead of looking for a new connection after a disconnect.
https://github.com/amazon-contributing/redis-rs/issues/144
> Send retries in multi-node reconnect to new connection.

- redis/src/client.rs
- redis/src/cmd.rs
- redis/src/commands/json.rs
- redis/src/commands/macros.rs
- redis/src/lib.rs
https://github.com/redis-rs/redis-rs/issues/1009
> Various documentation improvements.

- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_routing.rs
- redis/src/cluster_topology.rs
- redis/src/lib.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
Moved handling or parsing logic to a separate file, and allowed cluster connections to handle more esoteric forms of cluster slots return values.
> Slot parsing: Added handling to "?" and NULL hostnames in CLUSTER SLOTS.

- redis/src/aio/multiplexed_connection.rs
Added some documentation which can help users who need to close the underlying connection of a `MultiplexedConnection`.
https://github.com/redis-rs/redis-rs/issues/1236
> Improve documentation of multiplexed connection.

- .github/workflows/rust.yml
https://docs.github.com/en/actions/using-jobs/using-concurrency
> Cancel ongoing github actions on push.

- redis/src/aio/connection_manager.rs
https://github.com/redis-rs/redis-rs/issues/1307#issue-2503994237
Any where else this needs to be done? @jaymell
> Default for ConnectionManagerConfig

- redis/src/types.rs
- redis/tests/support/mod.rs
remove `?Sized` false constraint, since `To/FromRedisArgs` require `Sized`.
> Fix new lints

- redis/tests/support/mod.rs
fixes https://github.com/redis-rs/redis-rs/issues/1234
> Use should_panic macro on test_block_on_all_panics_from_spawns function

- Cargo.lock
- redis/CHANGELOG.md
- redis/Cargo.toml
- redis/src/aio/pubsub.rs
- redis/tests/test_async.rs
https://github.com/redis-rs/redis-rs/issues/1327
> Pubsub: Keep stream running after sink was closed.

- redis/src/parser.rs
Ensure we enforce max recursion depth across all types, not just arrays.
> Further limit parser recursion

- redis/src/aio/mod.rs
- redis/src/aio/pubsub.rs
https://github.com/redis-rs/redis-rs/issues/1365
> Expose the sink and stream parts of an async pubsub to the user.

- redis/src/connection.rs
- redis/tests/test_basic.rs
https://github.com/redis-rs/redis-rs/issues/1375
Because the timeouts instructed the client to skip the next message, once a message is received it is skipped and the pubsub times out again waiting for another message.
> Fix timeouts throwing Pubsub::get_message.

- redis/src/commands/mod.rs
- redis/tests/test_acl.rs
- doc valkey command https://valkey.io/commands/acl-dryrun/
- doc redis command https://redis.io/docs/latest/commands/acl-dryrun/
> implement command `DRYRUN`

- Cargo.lock
- redis/Cargo.toml
- redis/src/types.rs
- redis/tests/test_types.rs
https://github.com/redis-rs/redis-rs/issues/1358#issuecomment-2387876011
> Support for `hashbrown::HashMap` and `hashbrown::HashSet` 

- redis/tests/support/mod.rs
It wasn't obvious, because the test expects a panic, so the "wrong" panic was ignored.
> Fix test_block_on_all_panics_from_spawns consistently failing on async_std.

- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
https://valkey.io/commands/client-id/
> impl CLIENT ID

- redis/src/commands/mod.rs
- redis/tests/test_basic.rs
doc https://valkey.io/commands/client-setname/
> impl CLIENT SETNAME

- Cargo.lock
- redis/Cargo.toml
- redis/src/lib.rs
- redis/src/types.rs
- redis/tests/test_basic.rs
- redis/tests/test_sentinel.rs
- redis/tests/test_types.rs
resolve https://github.com/redis-rs/redis-rs/issues/1320
> feat: Add high level type for ROLE command

- redis/src/cluster.rs
- redis/tests/test_cluster.rs
- redis/tests/test_cluster_async.rs
This PR aligns the behavior of the sync cluster connection with the async connection - after a complete cluster disconnect, the connection will attempt to reconnect to the initial nodes and perform a topology refresh.
> Sync cluster - reconnect after complete disconnect.

- README.md
- redis/src/lib.rs
https://github.com/redis-rs/redis-rs/issues/1410
> Add docs clarifying connection pool usage.

- redis/src/aio/connection_manager.rs
- redis/src/aio/multiplexed_connection.rs
- redis/src/client.rs
This hopefully helps clarify some of the issues raised in https://github.com/redis-rs/redis-rs/issues/1435
> Clarify RESP3 subscription documentation.

- .github/workflows/rust.yml
- redis/src/connection.rs
- redis/src/parser.rs
- redis/src/types.rs
> test in CI against valkey 8.

- redis/src/types.rs
While clusters do implement retrying if you are using the non-cluster API you would need to do this by hand, which makes the RetryMethod API very useful.
I've tried to add appropriate comments onto things but if you think it needs extra clarification feel free to let me know and I'll update the PR.
> Expose RetryMethod to consumers

- redis/Cargo.toml
- redis/src/lib.rs
The purpose of this change is to make the documentation
around features clearer, and to prevent mistakes such
https://github.com/redis-rs/redis-rs/issues/1389
> Improve features and TLS docs.

- redis/src/cluster_routing.rs
- redis/tests/test_cluster_async.rs
https://github.com/redis-rs/redis-rs/issues/1482
> Fix routing for `PUBSUB SHARDNUMSUB`

- redis-test/src/server.rs
- redis/src/connection.rs
- redis/tests/test_basic.rs
Before this we've only timed out on TCP connection creation, not on sending the setup requests to the server.
https://github.com/redis-rs/redis-rs/issues/554
> Fix connection creation timeout.

- redis/src/cluster_async/mod.rs
The error message if all cluster connections fail currently throws away all detail about the specific connection attempts. The `RedisError` type isn't great about dealing with nested errors but I think it would be preferable to at least display one error reason, though ideally we might want to spell out all failures.
> feat: Include the reason for one connection failure if cluster connect fails

- redis/src/commands/mod.rs
> Improve docs around TTLs/ expiry times.

- redis/src/aio/multiplexed_connection.rs
- redis/src/cluster.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_client.rs
This ensures that a request that timed out won't be sent to the server.
https://github.com/redis-rs/redis-rs/issues/1541
> Timeout on queuing requests.

- .github/workflows/rust.yml
- redis/src/cluster_client.rs
- redis/src/sentinel.rs
Moved to my fork of flag-frenzy, since the official one is archived.
> Fix flag-frenzy not looking for warnings.

- redis/src/io/tcp.rs
https://github.com/redis-rs/redis-rs/issues/1571
> re-export socket2.

- redis/src/aio/connection.rs
- redis/src/aio/mod.rs
- redis/src/client.rs
- redis/src/cluster_async/mod.rs
- redis/src/cluster_client.rs
- redis/src/io/dns.rs
- redis/src/io/mod.rs
> Support custom DNS resolver for async client

- redis/src/cluster.rs
- redis/src/cluster_client.rs
Sry for the previous PR #1581, I found missing configuration for `ClusterConfig` and fix the docs.
> Add async dns resolver for cluster config and fix doc

- redis/src/aio/connection.rs
fixes https://github.com/redis-rs/redis-rs/issues/1597
> Fix error kind declaration.

- redis/src/aio/connection_manager.rs
- redis/src/caching/cache_manager.rs
- redis/src/caching/sharded_lru.rs
Patch enables CacheManager to be shared by multiple connections.
This will allow one CacheManager to be used by Cluster Connections,  `test_epoch_on_shared_cache_managers` can be checked for planned use.
> Add epoch for CacheManager

- redis/src/cmd.rs
This adds a `clear()` function, which clears the buffers but keeps any settings. It also makes the `write_packed_command()` function public, so the command can be serialized to an existing buffer.
> Allow for buffer reuse with `Cmd`

- redis/src/pipeline.rs
While working on a mocking `ConnectionLike` it at first was not straight forward to me why we use the offset/count that we do.
After the understanding what `atomic` does, it's clear.
But adding some explanation will hopefully help the next person who needs to understand them.
> Pipeline: Add comments explaining offset and count

- redis/src/commands/mod.rs
- redis/src/lib.rs
- redis/tests/test_basic.rs
Adds support for the extra options available in the ZADD command
> feat: support extended options for ZADD

- redis/src/commands/mod.rs
- redis/tests/test_acl.rs
- redis/tests/test_geospatial.rs
- redis/tests/test_streams.rs
Fixes
https://github.com/redis-rs/redis-rs/issues/1683
> Fix typed commands for submodules.

- .github/workflows/rust.yml
- redis-test/Cargo.toml
- redis/Cargo.toml
- redis/examples/async-connection-loss.rs
- redis/examples/async-scan.rs
- redis/examples/basic.rs
- redis/examples/geospatial.rs
- redis/src/caching/cache_manager.rs
- redis/src/connection.rs
https://github.com/redis-rs/redis-rs/issues/1688
> Run all examples as part of CI.

- redis/src/cmd.rs
https://github.com/redis-rs/redis-rs/issues/1644
> Replace assert with comment.

- redis/tests/support/mod.rs
Sometimes the runtimes don't wake up in order, so we wait until the panic happens.
> Fix flakey test.

- redis/src/lib.rs
- redis/src/sentinel.rs
- redis/tests/support/sentinel.rs
Align with the changes to `ConnectionInfo`  in https://github.com/redis-rs/redis-rs/pull/1669
> Use builder pattern for SentinelNodeConnectionInfo

- README.md
- redis/examples/async-pub-sub.rs
- redis/src/cluster_handling/async_connection/mod.rs
- redis/src/cluster_handling/sync_connection/mod.rs
- redis/src/lib.rs
- redis/src/sentinel.rs
We want more users to be aware of the typed traits, in order to save issues like https://github.com/redis-rs/redis-rs/issues/1730.
> Enhance visibility of typed traits in docs.

- redis/src/cmd.rs
These were written as part of a feature that is, so far, incomplete.
> Add Cmd tests.

- .github/workflows/rust.yml
- redis-test/Cargo.toml
- redis/Cargo.toml
- redis/src/cluster_handling/async_connection/mod.rs
- redis/src/cluster_handling/mod.rs
- redis/src/cluster_handling/sync_connection/mod.rs
- redis/src/commands/vector_sets.rs
- redis/src/pipeline.rs
Use references instead of some clones.
> Reduce number of clones.

- redis/CHANGELOG.md
- redis/src/commands/streams.rs
- redis/tests/test_acl.rs
- redis/tests/test_basic.rs
- redis/tests/test_streams.rs
https://github.com/redis-rs/redis-rs/issues/1798
> Fixed deserialization of autoclaim messages
